/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ru.testit.kotlin.adaptersapi.apis

import java.io.IOException
import okhttp3.Call
import okhttp3.HttpUrl

import ru.testit.kotlin.adaptersapi.models.AutoTestApiResult
import ru.testit.kotlin.adaptersapi.models.AutoTestCreateApiModel
import ru.testit.kotlin.adaptersapi.models.AutoTestModel
import ru.testit.kotlin.adaptersapi.models.AutoTestSearchApiModel
import ru.testit.kotlin.adaptersapi.models.AutoTestUpdateApiModel
import ru.testit.kotlin.adaptersapi.models.AutoTestWorkItemIdentifierApiResult
import ru.testit.kotlin.adaptersapi.models.Operation
import ru.testit.kotlin.adaptersapi.models.ProblemDetails
import ru.testit.kotlin.adaptersapi.models.ValidationProblemDetails
import ru.testit.kotlin.adaptersapi.models.WorkItemIdApiModel

import com.squareup.moshi.Json

import ru.testit.kotlin.adaptersapi.infrastructure.ApiClient
import ru.testit.kotlin.adaptersapi.infrastructure.ApiResponse
import ru.testit.kotlin.adaptersapi.infrastructure.ClientException
import ru.testit.kotlin.adaptersapi.infrastructure.ClientError
import ru.testit.kotlin.adaptersapi.infrastructure.ServerException
import ru.testit.kotlin.adaptersapi.infrastructure.ServerError
import ru.testit.kotlin.adaptersapi.infrastructure.MultiValueMap
import ru.testit.kotlin.adaptersapi.infrastructure.PartConfig
import ru.testit.kotlin.adaptersapi.infrastructure.RequestConfig
import ru.testit.kotlin.adaptersapi.infrastructure.RequestMethod
import ru.testit.kotlin.adaptersapi.infrastructure.ResponseType
import ru.testit.kotlin.adaptersapi.infrastructure.Success
import ru.testit.kotlin.adaptersapi.infrastructure.toMultiValue

open class AutoTestsApi(basePath: kotlin.String = defaultBasePath, client: Call.Factory = ApiClient.defaultClient) : ApiClient(basePath, client) {
    companion object {
        @JvmStatic
        val defaultBasePath: String by lazy {
            System.getProperties().getProperty(ApiClient.baseUrlKey, "http://localhost")
        }
    }

    /**
     * POST /adapters/autoTests/bulk
     * Create multiple autotests
     * 
     * @param autoTestCreateApiModel  (optional)
     * @return kotlin.collections.List<AutoTestApiResult>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun adaptersAutoTestsBulkPost(autoTestCreateApiModel: kotlin.collections.List<AutoTestCreateApiModel>? = null) : kotlin.collections.List<AutoTestApiResult> {
        val localVarResponse = adaptersAutoTestsBulkPostWithHttpInfo(autoTestCreateApiModel = autoTestCreateApiModel)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as kotlin.collections.List<AutoTestApiResult>
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /adapters/autoTests/bulk
     * Create multiple autotests
     * 
     * @param autoTestCreateApiModel  (optional)
     * @return ApiResponse<kotlin.collections.List<AutoTestApiResult>?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun adaptersAutoTestsBulkPostWithHttpInfo(autoTestCreateApiModel: kotlin.collections.List<AutoTestCreateApiModel>?) : ApiResponse<kotlin.collections.List<AutoTestApiResult>?> {
        val localVariableConfig = adaptersAutoTestsBulkPostRequestConfig(autoTestCreateApiModel = autoTestCreateApiModel)

        return request<kotlin.collections.List<AutoTestCreateApiModel>, kotlin.collections.List<AutoTestApiResult>>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation adaptersAutoTestsBulkPost
     *
     * @param autoTestCreateApiModel  (optional)
     * @return RequestConfig
     */
    fun adaptersAutoTestsBulkPostRequestConfig(autoTestCreateApiModel: kotlin.collections.List<AutoTestCreateApiModel>?) : RequestConfig<kotlin.collections.List<AutoTestCreateApiModel>> {
        val localVariableBody = autoTestCreateApiModel
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/adapters/autoTests/bulk",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * PUT /adapters/autoTests/bulk
     * Update multiple autotests
     * 
     * @param autoTestUpdateApiModel  (optional)
     * @return void
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun adaptersAutoTestsBulkPut(autoTestUpdateApiModel: kotlin.collections.List<AutoTestUpdateApiModel>? = null) : Unit {
        val localVarResponse = adaptersAutoTestsBulkPutWithHttpInfo(autoTestUpdateApiModel = autoTestUpdateApiModel)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> Unit
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * PUT /adapters/autoTests/bulk
     * Update multiple autotests
     * 
     * @param autoTestUpdateApiModel  (optional)
     * @return ApiResponse<Unit?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Throws(IllegalStateException::class, IOException::class)
    fun adaptersAutoTestsBulkPutWithHttpInfo(autoTestUpdateApiModel: kotlin.collections.List<AutoTestUpdateApiModel>?) : ApiResponse<Unit?> {
        val localVariableConfig = adaptersAutoTestsBulkPutRequestConfig(autoTestUpdateApiModel = autoTestUpdateApiModel)

        return request<kotlin.collections.List<AutoTestUpdateApiModel>, Unit>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation adaptersAutoTestsBulkPut
     *
     * @param autoTestUpdateApiModel  (optional)
     * @return RequestConfig
     */
    fun adaptersAutoTestsBulkPutRequestConfig(autoTestUpdateApiModel: kotlin.collections.List<AutoTestUpdateApiModel>?) : RequestConfig<kotlin.collections.List<AutoTestUpdateApiModel>> {
        val localVariableBody = autoTestUpdateApiModel
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.PUT,
            path = "/adapters/autoTests/bulk",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * GET /adapters/autoTests
     * 
     * 
     * @param projectId Project internal ID (optional)
     * @param externalId Autotest external ID (optional)
     * @param globalId Autotest global ID (optional)
     * @param namespace Namespace in which autotest is located (optional)
     * @param isNamespaceNull OBSOLETE: Use &#x60;includeEmptyNamespaces&#x60; instead (optional)
     * @param includeEmptyNamespaces If result must contain autotests without namespace (optional)
     * @param className Name of class in which autotest is located (optional)
     * @param isClassnameNull OBSOLETE: Use &#x60;includeEmptyClassNames&#x60; instead (optional)
     * @param includeEmptyClassNames If result must contain autotests without class (optional)
     * @param isDeleted OBSOLETE: Use &#x60;deleted&#x60; instead (optional)
     * @param deleted Is autotest deleted (optional)
     * @param labels Include only autotests with provided labels (optional)
     * @param stabilityMinimal OBSOLETE: Use &#x60;minStability&#x60; instead (optional)
     * @param minStability Minimum stability value of autotest (optional)
     * @param stabilityMaximal OBSOLETE: Use &#x60;maxStability&#x60; instead (optional)
     * @param maxStability Maximum stability value of autotest (optional)
     * @param isFlaky OBSOLETE: Use &#x60;flaky&#x60; instead (optional)
     * @param flaky Is autotest marked as \&quot;Flaky\&quot; (optional)
     * @param includeSteps If result must also include autotest steps (optional)
     * @param includeLabels If result must also include autotest labels (optional)
     * @param externalKey External key of autotest (optional)
     * @param skip Amount of items to be skipped (offset) (optional)
     * @param take Amount of items to be taken (limit) (optional)
     * @param orderBy SQL-like  ORDER BY statement (column1 ASC|DESC , column2 ASC|DESC) (optional)
     * @param searchField Property name for searching (optional)
     * @param searchValue Value for searching (optional)
     * @return kotlin.collections.List<AutoTestModel>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    @Deprecated(message = "This operation is deprecated.")
    fun adaptersAutoTestsGet(projectId: java.util.UUID? = null, externalId: kotlin.String? = null, globalId: kotlin.Long? = null, namespace: kotlin.String? = null, isNamespaceNull: kotlin.Boolean? = null, includeEmptyNamespaces: kotlin.Boolean? = null, className: kotlin.String? = null, isClassnameNull: kotlin.Boolean? = null, includeEmptyClassNames: kotlin.Boolean? = null, isDeleted: kotlin.Boolean? = null, deleted: kotlin.Boolean? = null, labels: kotlin.collections.List<kotlin.String>? = null, stabilityMinimal: kotlin.Int? = null, minStability: kotlin.Int? = null, stabilityMaximal: kotlin.Int? = null, maxStability: kotlin.Int? = null, isFlaky: kotlin.Boolean? = null, flaky: kotlin.Boolean? = null, includeSteps: kotlin.Boolean? = null, includeLabels: kotlin.Boolean? = null, externalKey: kotlin.String? = null, skip: kotlin.Int? = null, take: kotlin.Int? = null, orderBy: kotlin.String? = null, searchField: kotlin.String? = null, searchValue: kotlin.String? = null) : kotlin.collections.List<AutoTestModel> {
        @Suppress("DEPRECATION")
        val localVarResponse = adaptersAutoTestsGetWithHttpInfo(projectId = projectId, externalId = externalId, globalId = globalId, namespace = namespace, isNamespaceNull = isNamespaceNull, includeEmptyNamespaces = includeEmptyNamespaces, className = className, isClassnameNull = isClassnameNull, includeEmptyClassNames = includeEmptyClassNames, isDeleted = isDeleted, deleted = deleted, labels = labels, stabilityMinimal = stabilityMinimal, minStability = minStability, stabilityMaximal = stabilityMaximal, maxStability = maxStability, isFlaky = isFlaky, flaky = flaky, includeSteps = includeSteps, includeLabels = includeLabels, externalKey = externalKey, skip = skip, take = take, orderBy = orderBy, searchField = searchField, searchValue = searchValue)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as kotlin.collections.List<AutoTestModel>
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /adapters/autoTests
     * 
     * 
     * @param projectId Project internal ID (optional)
     * @param externalId Autotest external ID (optional)
     * @param globalId Autotest global ID (optional)
     * @param namespace Namespace in which autotest is located (optional)
     * @param isNamespaceNull OBSOLETE: Use &#x60;includeEmptyNamespaces&#x60; instead (optional)
     * @param includeEmptyNamespaces If result must contain autotests without namespace (optional)
     * @param className Name of class in which autotest is located (optional)
     * @param isClassnameNull OBSOLETE: Use &#x60;includeEmptyClassNames&#x60; instead (optional)
     * @param includeEmptyClassNames If result must contain autotests without class (optional)
     * @param isDeleted OBSOLETE: Use &#x60;deleted&#x60; instead (optional)
     * @param deleted Is autotest deleted (optional)
     * @param labels Include only autotests with provided labels (optional)
     * @param stabilityMinimal OBSOLETE: Use &#x60;minStability&#x60; instead (optional)
     * @param minStability Minimum stability value of autotest (optional)
     * @param stabilityMaximal OBSOLETE: Use &#x60;maxStability&#x60; instead (optional)
     * @param maxStability Maximum stability value of autotest (optional)
     * @param isFlaky OBSOLETE: Use &#x60;flaky&#x60; instead (optional)
     * @param flaky Is autotest marked as \&quot;Flaky\&quot; (optional)
     * @param includeSteps If result must also include autotest steps (optional)
     * @param includeLabels If result must also include autotest labels (optional)
     * @param externalKey External key of autotest (optional)
     * @param skip Amount of items to be skipped (offset) (optional)
     * @param take Amount of items to be taken (limit) (optional)
     * @param orderBy SQL-like  ORDER BY statement (column1 ASC|DESC , column2 ASC|DESC) (optional)
     * @param searchField Property name for searching (optional)
     * @param searchValue Value for searching (optional)
     * @return ApiResponse<kotlin.collections.List<AutoTestModel>?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    @Deprecated(message = "This operation is deprecated.")
    fun adaptersAutoTestsGetWithHttpInfo(projectId: java.util.UUID?, externalId: kotlin.String?, globalId: kotlin.Long?, namespace: kotlin.String?, isNamespaceNull: kotlin.Boolean?, includeEmptyNamespaces: kotlin.Boolean?, className: kotlin.String?, isClassnameNull: kotlin.Boolean?, includeEmptyClassNames: kotlin.Boolean?, isDeleted: kotlin.Boolean?, deleted: kotlin.Boolean?, labels: kotlin.collections.List<kotlin.String>?, stabilityMinimal: kotlin.Int?, minStability: kotlin.Int?, stabilityMaximal: kotlin.Int?, maxStability: kotlin.Int?, isFlaky: kotlin.Boolean?, flaky: kotlin.Boolean?, includeSteps: kotlin.Boolean?, includeLabels: kotlin.Boolean?, externalKey: kotlin.String?, skip: kotlin.Int?, take: kotlin.Int?, orderBy: kotlin.String?, searchField: kotlin.String?, searchValue: kotlin.String?) : ApiResponse<kotlin.collections.List<AutoTestModel>?> {
        @Suppress("DEPRECATION")
        val localVariableConfig = adaptersAutoTestsGetRequestConfig(projectId = projectId, externalId = externalId, globalId = globalId, namespace = namespace, isNamespaceNull = isNamespaceNull, includeEmptyNamespaces = includeEmptyNamespaces, className = className, isClassnameNull = isClassnameNull, includeEmptyClassNames = includeEmptyClassNames, isDeleted = isDeleted, deleted = deleted, labels = labels, stabilityMinimal = stabilityMinimal, minStability = minStability, stabilityMaximal = stabilityMaximal, maxStability = maxStability, isFlaky = isFlaky, flaky = flaky, includeSteps = includeSteps, includeLabels = includeLabels, externalKey = externalKey, skip = skip, take = take, orderBy = orderBy, searchField = searchField, searchValue = searchValue)

        return request<Unit, kotlin.collections.List<AutoTestModel>>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation adaptersAutoTestsGet
     *
     * @param projectId Project internal ID (optional)
     * @param externalId Autotest external ID (optional)
     * @param globalId Autotest global ID (optional)
     * @param namespace Namespace in which autotest is located (optional)
     * @param isNamespaceNull OBSOLETE: Use &#x60;includeEmptyNamespaces&#x60; instead (optional)
     * @param includeEmptyNamespaces If result must contain autotests without namespace (optional)
     * @param className Name of class in which autotest is located (optional)
     * @param isClassnameNull OBSOLETE: Use &#x60;includeEmptyClassNames&#x60; instead (optional)
     * @param includeEmptyClassNames If result must contain autotests without class (optional)
     * @param isDeleted OBSOLETE: Use &#x60;deleted&#x60; instead (optional)
     * @param deleted Is autotest deleted (optional)
     * @param labels Include only autotests with provided labels (optional)
     * @param stabilityMinimal OBSOLETE: Use &#x60;minStability&#x60; instead (optional)
     * @param minStability Minimum stability value of autotest (optional)
     * @param stabilityMaximal OBSOLETE: Use &#x60;maxStability&#x60; instead (optional)
     * @param maxStability Maximum stability value of autotest (optional)
     * @param isFlaky OBSOLETE: Use &#x60;flaky&#x60; instead (optional)
     * @param flaky Is autotest marked as \&quot;Flaky\&quot; (optional)
     * @param includeSteps If result must also include autotest steps (optional)
     * @param includeLabels If result must also include autotest labels (optional)
     * @param externalKey External key of autotest (optional)
     * @param skip Amount of items to be skipped (offset) (optional)
     * @param take Amount of items to be taken (limit) (optional)
     * @param orderBy SQL-like  ORDER BY statement (column1 ASC|DESC , column2 ASC|DESC) (optional)
     * @param searchField Property name for searching (optional)
     * @param searchValue Value for searching (optional)
     * @return RequestConfig
     */
    @Deprecated(message = "This operation is deprecated.")
    fun adaptersAutoTestsGetRequestConfig(projectId: java.util.UUID?, externalId: kotlin.String?, globalId: kotlin.Long?, namespace: kotlin.String?, isNamespaceNull: kotlin.Boolean?, includeEmptyNamespaces: kotlin.Boolean?, className: kotlin.String?, isClassnameNull: kotlin.Boolean?, includeEmptyClassNames: kotlin.Boolean?, isDeleted: kotlin.Boolean?, deleted: kotlin.Boolean?, labels: kotlin.collections.List<kotlin.String>?, stabilityMinimal: kotlin.Int?, minStability: kotlin.Int?, stabilityMaximal: kotlin.Int?, maxStability: kotlin.Int?, isFlaky: kotlin.Boolean?, flaky: kotlin.Boolean?, includeSteps: kotlin.Boolean?, includeLabels: kotlin.Boolean?, externalKey: kotlin.String?, skip: kotlin.Int?, take: kotlin.Int?, orderBy: kotlin.String?, searchField: kotlin.String?, searchValue: kotlin.String?) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                if (projectId != null) {
                    put("projectId", listOf(projectId.toString()))
                }
                if (externalId != null) {
                    put("externalId", listOf(externalId.toString()))
                }
                if (globalId != null) {
                    put("globalId", listOf(globalId.toString()))
                }
                if (namespace != null) {
                    put("namespace", listOf(namespace.toString()))
                }
                if (isNamespaceNull != null) {
                    put("isNamespaceNull", listOf(isNamespaceNull.toString()))
                }
                if (includeEmptyNamespaces != null) {
                    put("includeEmptyNamespaces", listOf(includeEmptyNamespaces.toString()))
                }
                if (className != null) {
                    put("className", listOf(className.toString()))
                }
                if (isClassnameNull != null) {
                    put("isClassnameNull", listOf(isClassnameNull.toString()))
                }
                if (includeEmptyClassNames != null) {
                    put("includeEmptyClassNames", listOf(includeEmptyClassNames.toString()))
                }
                if (isDeleted != null) {
                    put("isDeleted", listOf(isDeleted.toString()))
                }
                if (deleted != null) {
                    put("deleted", listOf(deleted.toString()))
                }
                if (labels != null) {
                    put("labels", toMultiValue(labels.toList(), "multi"))
                }
                if (stabilityMinimal != null) {
                    put("stabilityMinimal", listOf(stabilityMinimal.toString()))
                }
                if (minStability != null) {
                    put("minStability", listOf(minStability.toString()))
                }
                if (stabilityMaximal != null) {
                    put("stabilityMaximal", listOf(stabilityMaximal.toString()))
                }
                if (maxStability != null) {
                    put("maxStability", listOf(maxStability.toString()))
                }
                if (isFlaky != null) {
                    put("isFlaky", listOf(isFlaky.toString()))
                }
                if (flaky != null) {
                    put("flaky", listOf(flaky.toString()))
                }
                if (includeSteps != null) {
                    put("includeSteps", listOf(includeSteps.toString()))
                }
                if (includeLabels != null) {
                    put("includeLabels", listOf(includeLabels.toString()))
                }
                if (externalKey != null) {
                    put("externalKey", listOf(externalKey.toString()))
                }
                if (skip != null) {
                    put("Skip", listOf(skip.toString()))
                }
                if (take != null) {
                    put("Take", listOf(take.toString()))
                }
                if (orderBy != null) {
                    put("OrderBy", listOf(orderBy.toString()))
                }
                if (searchField != null) {
                    put("SearchField", listOf(searchField.toString()))
                }
                if (searchValue != null) {
                    put("SearchValue", listOf(searchValue.toString()))
                }
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/adapters/autoTests",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * GET /adapters/autoTests/{id}
     * Get autotest by internal or global ID
     * 
     * @param id Internal (UUID) or global (integer) identifier
     * @return AutoTestApiResult
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun adaptersAutoTestsIdGet(id: kotlin.String) : AutoTestApiResult {
        val localVarResponse = adaptersAutoTestsIdGetWithHttpInfo(id = id)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as AutoTestApiResult
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /adapters/autoTests/{id}
     * Get autotest by internal or global ID
     * 
     * @param id Internal (UUID) or global (integer) identifier
     * @return ApiResponse<AutoTestApiResult?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun adaptersAutoTestsIdGetWithHttpInfo(id: kotlin.String) : ApiResponse<AutoTestApiResult?> {
        val localVariableConfig = adaptersAutoTestsIdGetRequestConfig(id = id)

        return request<Unit, AutoTestApiResult>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation adaptersAutoTestsIdGet
     *
     * @param id Internal (UUID) or global (integer) identifier
     * @return RequestConfig
     */
    fun adaptersAutoTestsIdGetRequestConfig(id: kotlin.String) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/adapters/autoTests/{id}".replace("{"+"id"+"}", encodeURIComponent(id.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * PATCH /adapters/autoTests/{id}
     * Patch auto test
     * See &lt;a href&#x3D;\&quot;https://www.rfc-editor.org/rfc/rfc6902\&quot; target&#x3D;\&quot;_blank\&quot;&gt;RFC 6902: JavaScript Object Notation (JSON) Patch&lt;/a&gt; for details
     * @param id 
     * @param operation  (optional)
     * @return void
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun adaptersAutoTestsIdPatch(id: java.util.UUID, operation: kotlin.collections.List<Operation>? = null) : Unit {
        val localVarResponse = adaptersAutoTestsIdPatchWithHttpInfo(id = id, operation = operation)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> Unit
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * PATCH /adapters/autoTests/{id}
     * Patch auto test
     * See &lt;a href&#x3D;\&quot;https://www.rfc-editor.org/rfc/rfc6902\&quot; target&#x3D;\&quot;_blank\&quot;&gt;RFC 6902: JavaScript Object Notation (JSON) Patch&lt;/a&gt; for details
     * @param id 
     * @param operation  (optional)
     * @return ApiResponse<Unit?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Throws(IllegalStateException::class, IOException::class)
    fun adaptersAutoTestsIdPatchWithHttpInfo(id: java.util.UUID, operation: kotlin.collections.List<Operation>?) : ApiResponse<Unit?> {
        val localVariableConfig = adaptersAutoTestsIdPatchRequestConfig(id = id, operation = operation)

        return request<kotlin.collections.List<Operation>, Unit>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation adaptersAutoTestsIdPatch
     *
     * @param id 
     * @param operation  (optional)
     * @return RequestConfig
     */
    fun adaptersAutoTestsIdPatchRequestConfig(id: java.util.UUID, operation: kotlin.collections.List<Operation>?) : RequestConfig<kotlin.collections.List<Operation>> {
        val localVariableBody = operation
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.PATCH,
            path = "/adapters/autoTests/{id}".replace("{"+"id"+"}", encodeURIComponent(id.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * DELETE /adapters/autoTests/{id}/work-items
     * Unlink autotest from work item
     * 
     * @param id Internal (UUID) or global (integer) identifier
     * @param workItemId Internal (UUID) or global (integer) identifier (optional)
     * @return void
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun adaptersAutoTestsIdWorkItemsDelete(id: kotlin.String, workItemId: kotlin.String? = null) : Unit {
        val localVarResponse = adaptersAutoTestsIdWorkItemsDeleteWithHttpInfo(id = id, workItemId = workItemId)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> Unit
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * DELETE /adapters/autoTests/{id}/work-items
     * Unlink autotest from work item
     * 
     * @param id Internal (UUID) or global (integer) identifier
     * @param workItemId Internal (UUID) or global (integer) identifier (optional)
     * @return ApiResponse<Unit?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Throws(IllegalStateException::class, IOException::class)
    fun adaptersAutoTestsIdWorkItemsDeleteWithHttpInfo(id: kotlin.String, workItemId: kotlin.String?) : ApiResponse<Unit?> {
        val localVariableConfig = adaptersAutoTestsIdWorkItemsDeleteRequestConfig(id = id, workItemId = workItemId)

        return request<Unit, Unit>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation adaptersAutoTestsIdWorkItemsDelete
     *
     * @param id Internal (UUID) or global (integer) identifier
     * @param workItemId Internal (UUID) or global (integer) identifier (optional)
     * @return RequestConfig
     */
    fun adaptersAutoTestsIdWorkItemsDeleteRequestConfig(id: kotlin.String, workItemId: kotlin.String?) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                if (workItemId != null) {
                    put("workItemId", listOf(workItemId.toString()))
                }
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.DELETE,
            path = "/adapters/autoTests/{id}/work-items".replace("{"+"id"+"}", encodeURIComponent(id.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * GET /adapters/autoTests/{id}/work-items
     * Get work items linked to autotest
     * 
     * @param id Internal (UUID) or global (integer) identifier
     * @param isDeleted  (optional)
     * @param isWorkItemDeleted  (optional, default to false)
     * @return kotlin.collections.List<AutoTestWorkItemIdentifierApiResult>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun adaptersAutoTestsIdWorkItemsGet(id: kotlin.String, isDeleted: kotlin.Boolean? = null, isWorkItemDeleted: kotlin.Boolean? = false) : kotlin.collections.List<AutoTestWorkItemIdentifierApiResult> {
        val localVarResponse = adaptersAutoTestsIdWorkItemsGetWithHttpInfo(id = id, isDeleted = isDeleted, isWorkItemDeleted = isWorkItemDeleted)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as kotlin.collections.List<AutoTestWorkItemIdentifierApiResult>
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /adapters/autoTests/{id}/work-items
     * Get work items linked to autotest
     * 
     * @param id Internal (UUID) or global (integer) identifier
     * @param isDeleted  (optional)
     * @param isWorkItemDeleted  (optional, default to false)
     * @return ApiResponse<kotlin.collections.List<AutoTestWorkItemIdentifierApiResult>?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun adaptersAutoTestsIdWorkItemsGetWithHttpInfo(id: kotlin.String, isDeleted: kotlin.Boolean?, isWorkItemDeleted: kotlin.Boolean?) : ApiResponse<kotlin.collections.List<AutoTestWorkItemIdentifierApiResult>?> {
        val localVariableConfig = adaptersAutoTestsIdWorkItemsGetRequestConfig(id = id, isDeleted = isDeleted, isWorkItemDeleted = isWorkItemDeleted)

        return request<Unit, kotlin.collections.List<AutoTestWorkItemIdentifierApiResult>>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation adaptersAutoTestsIdWorkItemsGet
     *
     * @param id Internal (UUID) or global (integer) identifier
     * @param isDeleted  (optional)
     * @param isWorkItemDeleted  (optional, default to false)
     * @return RequestConfig
     */
    fun adaptersAutoTestsIdWorkItemsGetRequestConfig(id: kotlin.String, isDeleted: kotlin.Boolean?, isWorkItemDeleted: kotlin.Boolean?) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                if (isDeleted != null) {
                    put("isDeleted", listOf(isDeleted.toString()))
                }
                if (isWorkItemDeleted != null) {
                    put("isWorkItemDeleted", listOf(isWorkItemDeleted.toString()))
                }
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/adapters/autoTests/{id}/work-items".replace("{"+"id"+"}", encodeURIComponent(id.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * POST /adapters/autoTests/{id}/work-items
     * Link autotest with work items
     * 
     * @param id Internal (UUID) or global (integer) identifier
     * @param workItemIdApiModel  (optional)
     * @return void
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun adaptersAutoTestsIdWorkItemsPost(id: kotlin.String, workItemIdApiModel: WorkItemIdApiModel? = null) : Unit {
        val localVarResponse = adaptersAutoTestsIdWorkItemsPostWithHttpInfo(id = id, workItemIdApiModel = workItemIdApiModel)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> Unit
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /adapters/autoTests/{id}/work-items
     * Link autotest with work items
     * 
     * @param id Internal (UUID) or global (integer) identifier
     * @param workItemIdApiModel  (optional)
     * @return ApiResponse<Unit?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Throws(IllegalStateException::class, IOException::class)
    fun adaptersAutoTestsIdWorkItemsPostWithHttpInfo(id: kotlin.String, workItemIdApiModel: WorkItemIdApiModel?) : ApiResponse<Unit?> {
        val localVariableConfig = adaptersAutoTestsIdWorkItemsPostRequestConfig(id = id, workItemIdApiModel = workItemIdApiModel)

        return request<WorkItemIdApiModel, Unit>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation adaptersAutoTestsIdWorkItemsPost
     *
     * @param id Internal (UUID) or global (integer) identifier
     * @param workItemIdApiModel  (optional)
     * @return RequestConfig
     */
    fun adaptersAutoTestsIdWorkItemsPostRequestConfig(id: kotlin.String, workItemIdApiModel: WorkItemIdApiModel?) : RequestConfig<WorkItemIdApiModel> {
        val localVariableBody = workItemIdApiModel
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/adapters/autoTests/{id}/work-items".replace("{"+"id"+"}", encodeURIComponent(id.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * POST /adapters/autoTests
     * Create autotest
     * 
     * @param autoTestCreateApiModel  (optional)
     * @return AutoTestApiResult
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun adaptersAutoTestsPost(autoTestCreateApiModel: AutoTestCreateApiModel? = null) : AutoTestApiResult {
        val localVarResponse = adaptersAutoTestsPostWithHttpInfo(autoTestCreateApiModel = autoTestCreateApiModel)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as AutoTestApiResult
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /adapters/autoTests
     * Create autotest
     * 
     * @param autoTestCreateApiModel  (optional)
     * @return ApiResponse<AutoTestApiResult?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun adaptersAutoTestsPostWithHttpInfo(autoTestCreateApiModel: AutoTestCreateApiModel?) : ApiResponse<AutoTestApiResult?> {
        val localVariableConfig = adaptersAutoTestsPostRequestConfig(autoTestCreateApiModel = autoTestCreateApiModel)

        return request<AutoTestCreateApiModel, AutoTestApiResult>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation adaptersAutoTestsPost
     *
     * @param autoTestCreateApiModel  (optional)
     * @return RequestConfig
     */
    fun adaptersAutoTestsPostRequestConfig(autoTestCreateApiModel: AutoTestCreateApiModel?) : RequestConfig<AutoTestCreateApiModel> {
        val localVariableBody = autoTestCreateApiModel
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/adapters/autoTests",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * PUT /adapters/autoTests
     * Update autotest
     * 
     * @param autoTestUpdateApiModel  (optional)
     * @return void
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun adaptersAutoTestsPut(autoTestUpdateApiModel: AutoTestUpdateApiModel? = null) : Unit {
        val localVarResponse = adaptersAutoTestsPutWithHttpInfo(autoTestUpdateApiModel = autoTestUpdateApiModel)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> Unit
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * PUT /adapters/autoTests
     * Update autotest
     * 
     * @param autoTestUpdateApiModel  (optional)
     * @return ApiResponse<Unit?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Throws(IllegalStateException::class, IOException::class)
    fun adaptersAutoTestsPutWithHttpInfo(autoTestUpdateApiModel: AutoTestUpdateApiModel?) : ApiResponse<Unit?> {
        val localVariableConfig = adaptersAutoTestsPutRequestConfig(autoTestUpdateApiModel = autoTestUpdateApiModel)

        return request<AutoTestUpdateApiModel, Unit>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation adaptersAutoTestsPut
     *
     * @param autoTestUpdateApiModel  (optional)
     * @return RequestConfig
     */
    fun adaptersAutoTestsPutRequestConfig(autoTestUpdateApiModel: AutoTestUpdateApiModel?) : RequestConfig<AutoTestUpdateApiModel> {
        val localVariableBody = autoTestUpdateApiModel
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.PUT,
            path = "/adapters/autoTests",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * POST /adapters/autoTests/search
     * Search for autotests
     * 
     * @param skip Amount of items to be skipped (offset) (optional)
     * @param take Amount of items to be taken (limit) (optional)
     * @param orderBy SQL-like  ORDER BY statement (column1 ASC|DESC , column2 ASC|DESC) (optional)
     * @param searchField Property name for searching (optional)
     * @param searchValue Value for searching (optional)
     * @param autoTestSearchApiModel  (optional)
     * @return kotlin.collections.List<AutoTestApiResult>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun adaptersAutoTestsSearchPost(skip: kotlin.Int? = null, take: kotlin.Int? = null, orderBy: kotlin.String? = null, searchField: kotlin.String? = null, searchValue: kotlin.String? = null, autoTestSearchApiModel: AutoTestSearchApiModel? = null) : kotlin.collections.List<AutoTestApiResult> {
        val localVarResponse = adaptersAutoTestsSearchPostWithHttpInfo(skip = skip, take = take, orderBy = orderBy, searchField = searchField, searchValue = searchValue, autoTestSearchApiModel = autoTestSearchApiModel)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as kotlin.collections.List<AutoTestApiResult>
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /adapters/autoTests/search
     * Search for autotests
     * 
     * @param skip Amount of items to be skipped (offset) (optional)
     * @param take Amount of items to be taken (limit) (optional)
     * @param orderBy SQL-like  ORDER BY statement (column1 ASC|DESC , column2 ASC|DESC) (optional)
     * @param searchField Property name for searching (optional)
     * @param searchValue Value for searching (optional)
     * @param autoTestSearchApiModel  (optional)
     * @return ApiResponse<kotlin.collections.List<AutoTestApiResult>?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun adaptersAutoTestsSearchPostWithHttpInfo(skip: kotlin.Int?, take: kotlin.Int?, orderBy: kotlin.String?, searchField: kotlin.String?, searchValue: kotlin.String?, autoTestSearchApiModel: AutoTestSearchApiModel?) : ApiResponse<kotlin.collections.List<AutoTestApiResult>?> {
        val localVariableConfig = adaptersAutoTestsSearchPostRequestConfig(skip = skip, take = take, orderBy = orderBy, searchField = searchField, searchValue = searchValue, autoTestSearchApiModel = autoTestSearchApiModel)

        return request<AutoTestSearchApiModel, kotlin.collections.List<AutoTestApiResult>>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation adaptersAutoTestsSearchPost
     *
     * @param skip Amount of items to be skipped (offset) (optional)
     * @param take Amount of items to be taken (limit) (optional)
     * @param orderBy SQL-like  ORDER BY statement (column1 ASC|DESC , column2 ASC|DESC) (optional)
     * @param searchField Property name for searching (optional)
     * @param searchValue Value for searching (optional)
     * @param autoTestSearchApiModel  (optional)
     * @return RequestConfig
     */
    fun adaptersAutoTestsSearchPostRequestConfig(skip: kotlin.Int?, take: kotlin.Int?, orderBy: kotlin.String?, searchField: kotlin.String?, searchValue: kotlin.String?, autoTestSearchApiModel: AutoTestSearchApiModel?) : RequestConfig<AutoTestSearchApiModel> {
        val localVariableBody = autoTestSearchApiModel
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                if (skip != null) {
                    put("Skip", listOf(skip.toString()))
                }
                if (take != null) {
                    put("Take", listOf(take.toString()))
                }
                if (orderBy != null) {
                    put("OrderBy", listOf(orderBy.toString()))
                }
                if (searchField != null) {
                    put("SearchField", listOf(searchField.toString()))
                }
                if (searchValue != null) {
                    put("SearchValue", listOf(searchValue.toString()))
                }
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/adapters/autoTests/search",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }


    private fun encodeURIComponent(uriComponent: kotlin.String): kotlin.String =
        HttpUrl.Builder().scheme("http").host("localhost").addPathSegment(uriComponent).build().encodedPathSegments[0]
}
