/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ru.testit.kotlin.adaptersapi.apis

import java.io.IOException
import okhttp3.Call
import okhttp3.HttpUrl

import ru.testit.kotlin.adaptersapi.models.CustomAttributeApiResult
import ru.testit.kotlin.adaptersapi.models.CustomAttributeSearchApiModel
import ru.testit.kotlin.adaptersapi.models.CustomAttributeSearchApiResult
import ru.testit.kotlin.adaptersapi.models.GlobalCustomAttributePostApiModel
import ru.testit.kotlin.adaptersapi.models.GlobalCustomAttributeUpdateApiModel
import ru.testit.kotlin.adaptersapi.models.ProblemDetails
import ru.testit.kotlin.adaptersapi.models.ValidationProblemDetails

import com.squareup.moshi.Json

import ru.testit.kotlin.adaptersapi.infrastructure.ApiClient
import ru.testit.kotlin.adaptersapi.infrastructure.ApiResponse
import ru.testit.kotlin.adaptersapi.infrastructure.ClientException
import ru.testit.kotlin.adaptersapi.infrastructure.ClientError
import ru.testit.kotlin.adaptersapi.infrastructure.ServerException
import ru.testit.kotlin.adaptersapi.infrastructure.ServerError
import ru.testit.kotlin.adaptersapi.infrastructure.MultiValueMap
import ru.testit.kotlin.adaptersapi.infrastructure.PartConfig
import ru.testit.kotlin.adaptersapi.infrastructure.RequestConfig
import ru.testit.kotlin.adaptersapi.infrastructure.RequestMethod
import ru.testit.kotlin.adaptersapi.infrastructure.ResponseType
import ru.testit.kotlin.adaptersapi.infrastructure.Success
import ru.testit.kotlin.adaptersapi.infrastructure.toMultiValue

open class CustomAttributesApi(basePath: kotlin.String = defaultBasePath, client: Call.Factory = ApiClient.defaultClient) : ApiClient(basePath, client) {
    companion object {
        @JvmStatic
        val defaultBasePath: String by lazy {
            System.getProperties().getProperty(ApiClient.baseUrlKey, "http://localhost")
        }
    }

    /**
     * PUT /adapters/customAttributes/global/{id}
     * Update global attribute
     * 
     * @param id Unique ID of attribute
     * @param globalCustomAttributeUpdateApiModel  (optional)
     * @return CustomAttributeApiResult
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun adaptersCustomAttributesGlobalIdPut(id: java.util.UUID, globalCustomAttributeUpdateApiModel: GlobalCustomAttributeUpdateApiModel? = null) : CustomAttributeApiResult {
        val localVarResponse = adaptersCustomAttributesGlobalIdPutWithHttpInfo(id = id, globalCustomAttributeUpdateApiModel = globalCustomAttributeUpdateApiModel)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as CustomAttributeApiResult
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * PUT /adapters/customAttributes/global/{id}
     * Update global attribute
     * 
     * @param id Unique ID of attribute
     * @param globalCustomAttributeUpdateApiModel  (optional)
     * @return ApiResponse<CustomAttributeApiResult?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun adaptersCustomAttributesGlobalIdPutWithHttpInfo(id: java.util.UUID, globalCustomAttributeUpdateApiModel: GlobalCustomAttributeUpdateApiModel?) : ApiResponse<CustomAttributeApiResult?> {
        val localVariableConfig = adaptersCustomAttributesGlobalIdPutRequestConfig(id = id, globalCustomAttributeUpdateApiModel = globalCustomAttributeUpdateApiModel)

        return request<GlobalCustomAttributeUpdateApiModel, CustomAttributeApiResult>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation adaptersCustomAttributesGlobalIdPut
     *
     * @param id Unique ID of attribute
     * @param globalCustomAttributeUpdateApiModel  (optional)
     * @return RequestConfig
     */
    fun adaptersCustomAttributesGlobalIdPutRequestConfig(id: java.util.UUID, globalCustomAttributeUpdateApiModel: GlobalCustomAttributeUpdateApiModel?) : RequestConfig<GlobalCustomAttributeUpdateApiModel> {
        val localVariableBody = globalCustomAttributeUpdateApiModel
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.PUT,
            path = "/adapters/customAttributes/global/{id}".replace("{"+"id"+"}", encodeURIComponent(id.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * POST /adapters/customAttributes/global
     * Create global attribute
     * 
     * @param globalCustomAttributePostApiModel  (optional)
     * @return CustomAttributeApiResult
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun adaptersCustomAttributesGlobalPost(globalCustomAttributePostApiModel: GlobalCustomAttributePostApiModel? = null) : CustomAttributeApiResult {
        val localVarResponse = adaptersCustomAttributesGlobalPostWithHttpInfo(globalCustomAttributePostApiModel = globalCustomAttributePostApiModel)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as CustomAttributeApiResult
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /adapters/customAttributes/global
     * Create global attribute
     * 
     * @param globalCustomAttributePostApiModel  (optional)
     * @return ApiResponse<CustomAttributeApiResult?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun adaptersCustomAttributesGlobalPostWithHttpInfo(globalCustomAttributePostApiModel: GlobalCustomAttributePostApiModel?) : ApiResponse<CustomAttributeApiResult?> {
        val localVariableConfig = adaptersCustomAttributesGlobalPostRequestConfig(globalCustomAttributePostApiModel = globalCustomAttributePostApiModel)

        return request<GlobalCustomAttributePostApiModel, CustomAttributeApiResult>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation adaptersCustomAttributesGlobalPost
     *
     * @param globalCustomAttributePostApiModel  (optional)
     * @return RequestConfig
     */
    fun adaptersCustomAttributesGlobalPostRequestConfig(globalCustomAttributePostApiModel: GlobalCustomAttributePostApiModel?) : RequestConfig<GlobalCustomAttributePostApiModel> {
        val localVariableBody = globalCustomAttributePostApiModel
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/adapters/customAttributes/global",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * GET /adapters/customAttributes/{id}
     * Get attribute by ID
     * 
     * @param id Unique ID of attribute
     * @return CustomAttributeApiResult
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun adaptersCustomAttributesIdGet(id: java.util.UUID) : CustomAttributeApiResult {
        val localVarResponse = adaptersCustomAttributesIdGetWithHttpInfo(id = id)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as CustomAttributeApiResult
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /adapters/customAttributes/{id}
     * Get attribute by ID
     * 
     * @param id Unique ID of attribute
     * @return ApiResponse<CustomAttributeApiResult?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun adaptersCustomAttributesIdGetWithHttpInfo(id: java.util.UUID) : ApiResponse<CustomAttributeApiResult?> {
        val localVariableConfig = adaptersCustomAttributesIdGetRequestConfig(id = id)

        return request<Unit, CustomAttributeApiResult>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation adaptersCustomAttributesIdGet
     *
     * @param id Unique ID of attribute
     * @return RequestConfig
     */
    fun adaptersCustomAttributesIdGetRequestConfig(id: java.util.UUID) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/adapters/customAttributes/{id}".replace("{"+"id"+"}", encodeURIComponent(id.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * POST /adapters/customAttributes/search
     * Search for attributes
     * 
     * @param skip Amount of items to be skipped (offset) (optional)
     * @param take Amount of items to be taken (limit) (optional)
     * @param orderBy SQL-like  ORDER BY statement (column1 ASC|DESC , column2 ASC|DESC) (optional)
     * @param searchField Property name for searching (optional)
     * @param searchValue Value for searching (optional)
     * @param customAttributeSearchApiModel  (optional)
     * @return kotlin.collections.List<CustomAttributeSearchApiResult>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun adaptersCustomAttributesSearchPost(skip: kotlin.Int? = null, take: kotlin.Int? = null, orderBy: kotlin.String? = null, searchField: kotlin.String? = null, searchValue: kotlin.String? = null, customAttributeSearchApiModel: CustomAttributeSearchApiModel? = null) : kotlin.collections.List<CustomAttributeSearchApiResult> {
        val localVarResponse = adaptersCustomAttributesSearchPostWithHttpInfo(skip = skip, take = take, orderBy = orderBy, searchField = searchField, searchValue = searchValue, customAttributeSearchApiModel = customAttributeSearchApiModel)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as kotlin.collections.List<CustomAttributeSearchApiResult>
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /adapters/customAttributes/search
     * Search for attributes
     * 
     * @param skip Amount of items to be skipped (offset) (optional)
     * @param take Amount of items to be taken (limit) (optional)
     * @param orderBy SQL-like  ORDER BY statement (column1 ASC|DESC , column2 ASC|DESC) (optional)
     * @param searchField Property name for searching (optional)
     * @param searchValue Value for searching (optional)
     * @param customAttributeSearchApiModel  (optional)
     * @return ApiResponse<kotlin.collections.List<CustomAttributeSearchApiResult>?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun adaptersCustomAttributesSearchPostWithHttpInfo(skip: kotlin.Int?, take: kotlin.Int?, orderBy: kotlin.String?, searchField: kotlin.String?, searchValue: kotlin.String?, customAttributeSearchApiModel: CustomAttributeSearchApiModel?) : ApiResponse<kotlin.collections.List<CustomAttributeSearchApiResult>?> {
        val localVariableConfig = adaptersCustomAttributesSearchPostRequestConfig(skip = skip, take = take, orderBy = orderBy, searchField = searchField, searchValue = searchValue, customAttributeSearchApiModel = customAttributeSearchApiModel)

        return request<CustomAttributeSearchApiModel, kotlin.collections.List<CustomAttributeSearchApiResult>>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation adaptersCustomAttributesSearchPost
     *
     * @param skip Amount of items to be skipped (offset) (optional)
     * @param take Amount of items to be taken (limit) (optional)
     * @param orderBy SQL-like  ORDER BY statement (column1 ASC|DESC , column2 ASC|DESC) (optional)
     * @param searchField Property name for searching (optional)
     * @param searchValue Value for searching (optional)
     * @param customAttributeSearchApiModel  (optional)
     * @return RequestConfig
     */
    fun adaptersCustomAttributesSearchPostRequestConfig(skip: kotlin.Int?, take: kotlin.Int?, orderBy: kotlin.String?, searchField: kotlin.String?, searchValue: kotlin.String?, customAttributeSearchApiModel: CustomAttributeSearchApiModel?) : RequestConfig<CustomAttributeSearchApiModel> {
        val localVariableBody = customAttributeSearchApiModel
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                if (skip != null) {
                    put("Skip", listOf(skip.toString()))
                }
                if (take != null) {
                    put("Take", listOf(take.toString()))
                }
                if (orderBy != null) {
                    put("OrderBy", listOf(orderBy.toString()))
                }
                if (searchField != null) {
                    put("SearchField", listOf(searchField.toString()))
                }
                if (searchValue != null) {
                    put("SearchValue", listOf(searchValue.toString()))
                }
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/adapters/customAttributes/search",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }


    private fun encodeURIComponent(uriComponent: kotlin.String): kotlin.String =
        HttpUrl.Builder().scheme("http").host("localhost").addPathSegment(uriComponent).build().encodedPathSegments[0]
}
