/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ru.testit.kotlin.adaptersapi.apis

import java.io.IOException
import okhttp3.Call
import okhttp3.HttpUrl

import ru.testit.kotlin.adaptersapi.models.CreateParameterApiModel
import ru.testit.kotlin.adaptersapi.models.ParameterApiResult
import ru.testit.kotlin.adaptersapi.models.ParametersFilterApiModel
import ru.testit.kotlin.adaptersapi.models.ProblemDetails
import ru.testit.kotlin.adaptersapi.models.ValidationProblemDetails

import com.squareup.moshi.Json

import ru.testit.kotlin.adaptersapi.infrastructure.ApiClient
import ru.testit.kotlin.adaptersapi.infrastructure.ApiResponse
import ru.testit.kotlin.adaptersapi.infrastructure.ClientException
import ru.testit.kotlin.adaptersapi.infrastructure.ClientError
import ru.testit.kotlin.adaptersapi.infrastructure.ServerException
import ru.testit.kotlin.adaptersapi.infrastructure.ServerError
import ru.testit.kotlin.adaptersapi.infrastructure.MultiValueMap
import ru.testit.kotlin.adaptersapi.infrastructure.PartConfig
import ru.testit.kotlin.adaptersapi.infrastructure.RequestConfig
import ru.testit.kotlin.adaptersapi.infrastructure.RequestMethod
import ru.testit.kotlin.adaptersapi.infrastructure.ResponseType
import ru.testit.kotlin.adaptersapi.infrastructure.Success
import ru.testit.kotlin.adaptersapi.infrastructure.toMultiValue

open class ParametersApi(basePath: kotlin.String = defaultBasePath, client: Call.Factory = ApiClient.defaultClient) : ApiClient(basePath, client) {
    companion object {
        @JvmStatic
        val defaultBasePath: String by lazy {
            System.getProperties().getProperty(ApiClient.baseUrlKey, "http://localhost")
        }
    }

    /**
     * GET /adapters/parameters/{id}
     * Get parameter by ID
     * 
     * @param id 
     * @return ParameterApiResult
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun adaptersParametersIdGet(id: java.util.UUID) : ParameterApiResult {
        val localVarResponse = adaptersParametersIdGetWithHttpInfo(id = id)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as ParameterApiResult
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /adapters/parameters/{id}
     * Get parameter by ID
     * 
     * @param id 
     * @return ApiResponse<ParameterApiResult?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun adaptersParametersIdGetWithHttpInfo(id: java.util.UUID) : ApiResponse<ParameterApiResult?> {
        val localVariableConfig = adaptersParametersIdGetRequestConfig(id = id)

        return request<Unit, ParameterApiResult>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation adaptersParametersIdGet
     *
     * @param id 
     * @return RequestConfig
     */
    fun adaptersParametersIdGetRequestConfig(id: java.util.UUID) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/adapters/parameters/{id}".replace("{"+"id"+"}", encodeURIComponent(id.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * POST /adapters/parameters
     * Create parameter
     * 
     * @param createParameterApiModel  (optional)
     * @return ParameterApiResult
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun adaptersParametersPost(createParameterApiModel: CreateParameterApiModel? = null) : ParameterApiResult {
        val localVarResponse = adaptersParametersPostWithHttpInfo(createParameterApiModel = createParameterApiModel)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as ParameterApiResult
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /adapters/parameters
     * Create parameter
     * 
     * @param createParameterApiModel  (optional)
     * @return ApiResponse<ParameterApiResult?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun adaptersParametersPostWithHttpInfo(createParameterApiModel: CreateParameterApiModel?) : ApiResponse<ParameterApiResult?> {
        val localVariableConfig = adaptersParametersPostRequestConfig(createParameterApiModel = createParameterApiModel)

        return request<CreateParameterApiModel, ParameterApiResult>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation adaptersParametersPost
     *
     * @param createParameterApiModel  (optional)
     * @return RequestConfig
     */
    fun adaptersParametersPostRequestConfig(createParameterApiModel: CreateParameterApiModel?) : RequestConfig<CreateParameterApiModel> {
        val localVariableBody = createParameterApiModel
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/adapters/parameters",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * POST /adapters/parameters/search
     * Search for parameters
     * 
     * @param skip Amount of items to be skipped (offset) (optional)
     * @param take Amount of items to be taken (limit) (optional)
     * @param orderBy SQL-like  ORDER BY statement (column1 ASC|DESC , column2 ASC|DESC) (optional)
     * @param searchField Property name for searching (optional)
     * @param searchValue Value for searching (optional)
     * @param parametersFilterApiModel  (optional)
     * @return kotlin.collections.List<ParameterApiResult>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun adaptersParametersSearchPost(skip: kotlin.Int? = null, take: kotlin.Int? = null, orderBy: kotlin.String? = null, searchField: kotlin.String? = null, searchValue: kotlin.String? = null, parametersFilterApiModel: ParametersFilterApiModel? = null) : kotlin.collections.List<ParameterApiResult> {
        val localVarResponse = adaptersParametersSearchPostWithHttpInfo(skip = skip, take = take, orderBy = orderBy, searchField = searchField, searchValue = searchValue, parametersFilterApiModel = parametersFilterApiModel)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as kotlin.collections.List<ParameterApiResult>
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /adapters/parameters/search
     * Search for parameters
     * 
     * @param skip Amount of items to be skipped (offset) (optional)
     * @param take Amount of items to be taken (limit) (optional)
     * @param orderBy SQL-like  ORDER BY statement (column1 ASC|DESC , column2 ASC|DESC) (optional)
     * @param searchField Property name for searching (optional)
     * @param searchValue Value for searching (optional)
     * @param parametersFilterApiModel  (optional)
     * @return ApiResponse<kotlin.collections.List<ParameterApiResult>?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun adaptersParametersSearchPostWithHttpInfo(skip: kotlin.Int?, take: kotlin.Int?, orderBy: kotlin.String?, searchField: kotlin.String?, searchValue: kotlin.String?, parametersFilterApiModel: ParametersFilterApiModel?) : ApiResponse<kotlin.collections.List<ParameterApiResult>?> {
        val localVariableConfig = adaptersParametersSearchPostRequestConfig(skip = skip, take = take, orderBy = orderBy, searchField = searchField, searchValue = searchValue, parametersFilterApiModel = parametersFilterApiModel)

        return request<ParametersFilterApiModel, kotlin.collections.List<ParameterApiResult>>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation adaptersParametersSearchPost
     *
     * @param skip Amount of items to be skipped (offset) (optional)
     * @param take Amount of items to be taken (limit) (optional)
     * @param orderBy SQL-like  ORDER BY statement (column1 ASC|DESC , column2 ASC|DESC) (optional)
     * @param searchField Property name for searching (optional)
     * @param searchValue Value for searching (optional)
     * @param parametersFilterApiModel  (optional)
     * @return RequestConfig
     */
    fun adaptersParametersSearchPostRequestConfig(skip: kotlin.Int?, take: kotlin.Int?, orderBy: kotlin.String?, searchField: kotlin.String?, searchValue: kotlin.String?, parametersFilterApiModel: ParametersFilterApiModel?) : RequestConfig<ParametersFilterApiModel> {
        val localVariableBody = parametersFilterApiModel
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                if (skip != null) {
                    put("Skip", listOf(skip.toString()))
                }
                if (take != null) {
                    put("Take", listOf(take.toString()))
                }
                if (orderBy != null) {
                    put("OrderBy", listOf(orderBy.toString()))
                }
                if (searchField != null) {
                    put("SearchField", listOf(searchField.toString()))
                }
                if (searchValue != null) {
                    put("SearchValue", listOf(searchValue.toString()))
                }
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/adapters/parameters/search",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }


    private fun encodeURIComponent(uriComponent: kotlin.String): kotlin.String =
        HttpUrl.Builder().scheme("http").host("localhost").addPathSegment(uriComponent).build().encodedPathSegments[0]
}
