/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ru.testit.kotlin.adaptersapi.apis

import java.io.IOException
import okhttp3.Call
import okhttp3.HttpUrl

import ru.testit.kotlin.adaptersapi.models.ProblemDetails
import ru.testit.kotlin.adaptersapi.models.TestResultResponse
import ru.testit.kotlin.adaptersapi.models.TestResultShortResponse
import ru.testit.kotlin.adaptersapi.models.TestResultUpdateRequest
import ru.testit.kotlin.adaptersapi.models.TestResultsFilterApiModel
import ru.testit.kotlin.adaptersapi.models.ValidationProblemDetails

import com.squareup.moshi.Json

import ru.testit.kotlin.adaptersapi.infrastructure.ApiClient
import ru.testit.kotlin.adaptersapi.infrastructure.ApiResponse
import ru.testit.kotlin.adaptersapi.infrastructure.ClientException
import ru.testit.kotlin.adaptersapi.infrastructure.ClientError
import ru.testit.kotlin.adaptersapi.infrastructure.ServerException
import ru.testit.kotlin.adaptersapi.infrastructure.ServerError
import ru.testit.kotlin.adaptersapi.infrastructure.MultiValueMap
import ru.testit.kotlin.adaptersapi.infrastructure.PartConfig
import ru.testit.kotlin.adaptersapi.infrastructure.RequestConfig
import ru.testit.kotlin.adaptersapi.infrastructure.RequestMethod
import ru.testit.kotlin.adaptersapi.infrastructure.ResponseType
import ru.testit.kotlin.adaptersapi.infrastructure.Success
import ru.testit.kotlin.adaptersapi.infrastructure.toMultiValue

open class TestResultsApi(basePath: kotlin.String = defaultBasePath, client: Call.Factory = ApiClient.defaultClient) : ApiClient(basePath, client) {
    companion object {
        @JvmStatic
        val defaultBasePath: String by lazy {
            System.getProperties().getProperty(ApiClient.baseUrlKey, "http://localhost")
        }
    }

    /**
     * GET /adapters/testResults/{id}
     * Get test result by ID
     * 
     * @param id 
     * @return TestResultResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun adaptersTestResultsIdGet(id: java.util.UUID) : TestResultResponse {
        val localVarResponse = adaptersTestResultsIdGetWithHttpInfo(id = id)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as TestResultResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /adapters/testResults/{id}
     * Get test result by ID
     * 
     * @param id 
     * @return ApiResponse<TestResultResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun adaptersTestResultsIdGetWithHttpInfo(id: java.util.UUID) : ApiResponse<TestResultResponse?> {
        val localVariableConfig = adaptersTestResultsIdGetRequestConfig(id = id)

        return request<Unit, TestResultResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation adaptersTestResultsIdGet
     *
     * @param id 
     * @return RequestConfig
     */
    fun adaptersTestResultsIdGetRequestConfig(id: java.util.UUID) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/adapters/testResults/{id}".replace("{"+"id"+"}", encodeURIComponent(id.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * PUT /adapters/testResults/{id}
     * Edit test result by ID
     * 
     * @param id 
     * @param testResultUpdateRequest  (optional)
     * @return void
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun adaptersTestResultsIdPut(id: java.util.UUID, testResultUpdateRequest: TestResultUpdateRequest? = null) : Unit {
        val localVarResponse = adaptersTestResultsIdPutWithHttpInfo(id = id, testResultUpdateRequest = testResultUpdateRequest)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> Unit
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * PUT /adapters/testResults/{id}
     * Edit test result by ID
     * 
     * @param id 
     * @param testResultUpdateRequest  (optional)
     * @return ApiResponse<Unit?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Throws(IllegalStateException::class, IOException::class)
    fun adaptersTestResultsIdPutWithHttpInfo(id: java.util.UUID, testResultUpdateRequest: TestResultUpdateRequest?) : ApiResponse<Unit?> {
        val localVariableConfig = adaptersTestResultsIdPutRequestConfig(id = id, testResultUpdateRequest = testResultUpdateRequest)

        return request<TestResultUpdateRequest, Unit>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation adaptersTestResultsIdPut
     *
     * @param id 
     * @param testResultUpdateRequest  (optional)
     * @return RequestConfig
     */
    fun adaptersTestResultsIdPutRequestConfig(id: java.util.UUID, testResultUpdateRequest: TestResultUpdateRequest?) : RequestConfig<TestResultUpdateRequest> {
        val localVariableBody = testResultUpdateRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.PUT,
            path = "/adapters/testResults/{id}".replace("{"+"id"+"}", encodeURIComponent(id.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * POST /adapters/testResults/search
     * Search for test results
     * 
     * @param skip Amount of items to be skipped (offset) (optional)
     * @param take Amount of items to be taken (limit) (optional)
     * @param orderBy SQL-like  ORDER BY statement (column1 ASC|DESC , column2 ASC|DESC) (optional)
     * @param searchField Property name for searching (optional)
     * @param searchValue Value for searching (optional)
     * @param testResultsFilterApiModel  (optional)
     * @return kotlin.collections.List<TestResultShortResponse>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun adaptersTestResultsSearchPost(skip: kotlin.Int? = null, take: kotlin.Int? = null, orderBy: kotlin.String? = null, searchField: kotlin.String? = null, searchValue: kotlin.String? = null, testResultsFilterApiModel: TestResultsFilterApiModel? = null) : kotlin.collections.List<TestResultShortResponse> {
        val localVarResponse = adaptersTestResultsSearchPostWithHttpInfo(skip = skip, take = take, orderBy = orderBy, searchField = searchField, searchValue = searchValue, testResultsFilterApiModel = testResultsFilterApiModel)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as kotlin.collections.List<TestResultShortResponse>
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /adapters/testResults/search
     * Search for test results
     * 
     * @param skip Amount of items to be skipped (offset) (optional)
     * @param take Amount of items to be taken (limit) (optional)
     * @param orderBy SQL-like  ORDER BY statement (column1 ASC|DESC , column2 ASC|DESC) (optional)
     * @param searchField Property name for searching (optional)
     * @param searchValue Value for searching (optional)
     * @param testResultsFilterApiModel  (optional)
     * @return ApiResponse<kotlin.collections.List<TestResultShortResponse>?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun adaptersTestResultsSearchPostWithHttpInfo(skip: kotlin.Int?, take: kotlin.Int?, orderBy: kotlin.String?, searchField: kotlin.String?, searchValue: kotlin.String?, testResultsFilterApiModel: TestResultsFilterApiModel?) : ApiResponse<kotlin.collections.List<TestResultShortResponse>?> {
        val localVariableConfig = adaptersTestResultsSearchPostRequestConfig(skip = skip, take = take, orderBy = orderBy, searchField = searchField, searchValue = searchValue, testResultsFilterApiModel = testResultsFilterApiModel)

        return request<TestResultsFilterApiModel, kotlin.collections.List<TestResultShortResponse>>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation adaptersTestResultsSearchPost
     *
     * @param skip Amount of items to be skipped (offset) (optional)
     * @param take Amount of items to be taken (limit) (optional)
     * @param orderBy SQL-like  ORDER BY statement (column1 ASC|DESC , column2 ASC|DESC) (optional)
     * @param searchField Property name for searching (optional)
     * @param searchValue Value for searching (optional)
     * @param testResultsFilterApiModel  (optional)
     * @return RequestConfig
     */
    fun adaptersTestResultsSearchPostRequestConfig(skip: kotlin.Int?, take: kotlin.Int?, orderBy: kotlin.String?, searchField: kotlin.String?, searchValue: kotlin.String?, testResultsFilterApiModel: TestResultsFilterApiModel?) : RequestConfig<TestResultsFilterApiModel> {
        val localVariableBody = testResultsFilterApiModel
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                if (skip != null) {
                    put("Skip", listOf(skip.toString()))
                }
                if (take != null) {
                    put("Take", listOf(take.toString()))
                }
                if (orderBy != null) {
                    put("OrderBy", listOf(orderBy.toString()))
                }
                if (searchField != null) {
                    put("SearchField", listOf(searchField.toString()))
                }
                if (searchValue != null) {
                    put("SearchValue", listOf(searchValue.toString()))
                }
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/adapters/testResults/search",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }


    private fun encodeURIComponent(uriComponent: kotlin.String): kotlin.String =
        HttpUrl.Builder().scheme("http").host("localhost").addPathSegment(uriComponent).build().encodedPathSegments[0]
}
