version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    target-branch: "next"
    schedule:
      interval: "monthly"

  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "next"
    schedule:
      interval: "monthly"
