package ru.testit.management.parsers.regexps

object BehaveRegexp {
    const val ANNOTATION_SEPARATOR = "\\."
    const val KEY_VALUE_SEPARATOR = ":"
    const val EVERYTHING_AFTER_ANNOTATION = "[^\\s]{1,}"
    const val ALLURE_OBJECT = "allure"
    const val ALLURE_METHOD = ALLURE_OBJECT + ANNOTATION_SEPARATOR
    const val ALLURE_LINK_LABEL_NAME = "link"
    const val ALLURE_ISSUE_LABEL_NAME = "issue"
    const val ALLURE_TMS_LABEL_NAME = "tms"
    const val ALLURE_LINK = ALLURE_METHOD + ALLURE_LINK_LABEL_NAME + EVERYTHING_AFTER_ANNOTATION
    const val ALLURE_ISSUE = ALLURE_METHOD + ALLURE_ISSUE_LABEL_NAME + EVERYTHING_AFTER_ANNOTATION
    const val ALLURE_TESTCASE = ALLURE_METHOD + ALLURE_TMS_LABEL_NAME + EVERYTHING_AFTER_ANNOTATION
    const val ALLURE_EPIC_LABEL_NAME = "epic"
    const val ALLURE_STORY_LABEL_NAME = "story"
    const val ALLURE_PARENT_SUITE_LABEL_NAME = "parentSuite"
    const val ALLURE_SUITE_LABEL_NAME = "suite"
    const val ALLURE_SUB_SUITE_LABEL_NAME = "subSuite"
    const val ALLURE_PACKAGE_LABEL_NAME = "package"
    const val ALLURE_TEST_CLASS_LABEL_NAME = "testClass"
    const val ALLURE_TEST_METHOD_LABEL_NAME = "testMethod"
    const val LABEL_OTHER_FUNCTIONS_NAMES = "(?!" + ALLURE_EPIC_LABEL_NAME + "|" +
            ALLURE_STORY_LABEL_NAME + "|" + ALLURE_PARENT_SUITE_LABEL_NAME + "|" + ALLURE_SUITE_LABEL_NAME + "|" +
            ALLURE_SUB_SUITE_LABEL_NAME + "|" + ALLURE_PACKAGE_LABEL_NAME + "|" + ALLURE_TEST_CLASS_LABEL_NAME + "|" +
            ALLURE_TEST_METHOD_LABEL_NAME + ")"
    const val ALLURE_LABEL = ALLURE_METHOD + "label" + "[$ANNOTATION_SEPARATOR|$KEY_VALUE_SEPARATOR]"
    const val ALLURE_EPIC = ALLURE_LABEL + ALLURE_EPIC_LABEL_NAME + KEY_VALUE_SEPARATOR
    const val ALLURE_STORY = ALLURE_LABEL + ALLURE_STORY_LABEL_NAME + KEY_VALUE_SEPARATOR
    const val ALLURE_PARENT_SUITE = ALLURE_LABEL + ALLURE_PARENT_SUITE_LABEL_NAME + KEY_VALUE_SEPARATOR
    const val ALLURE_SUITE = ALLURE_LABEL + ALLURE_SUITE_LABEL_NAME + KEY_VALUE_SEPARATOR
    const val ALLURE_SUB_SUITE = ALLURE_LABEL + ALLURE_SUB_SUITE_LABEL_NAME + KEY_VALUE_SEPARATOR
    const val ALLURE_PACKAGE = ALLURE_LABEL + ALLURE_PACKAGE_LABEL_NAME + KEY_VALUE_SEPARATOR
    const val ALLURE_TEST_CLASS = ALLURE_LABEL + ALLURE_TEST_CLASS_LABEL_NAME + KEY_VALUE_SEPARATOR
    const val ALLURE_TEST_METHOD = ALLURE_LABEL + ALLURE_TEST_METHOD_LABEL_NAME + KEY_VALUE_SEPARATOR
    const val ALLURE_OTHER_FUNCTIONS_LABELS = ALLURE_LABEL + LABEL_OTHER_FUNCTIONS_NAMES +
            EVERYTHING_AFTER_ANNOTATION

    const val LINK_NAME_ANNOTATION_NAME = "name"
    const val LINK_URL_ANNOTATION_NAME = "url"
    const val LINK_NAME_ANNOTATION = "(\\." +
            "(?!$ALLURE_LINK_LABEL_NAME|$ALLURE_ISSUE_LABEL_NAME|$ALLURE_TMS_LABEL_NAME)" +
            "(?<$LINK_NAME_ANNOTATION_NAME>[^\\s.:]+)" +
            ")?:"
    const val LINK_URL_ANNOTATION = ":(?<$LINK_URL_ANNOTATION_NAME>\\S+)"
    const val LABEL_VALUE_ANNOTATION_NAME = "value"
    const val LABEL_VALUE_ANNOTATION = "label[.|:](?<$LABEL_VALUE_ANNOTATION_NAME>\\S+)"

    const val IMPORT_ALLURE_OBJECT = "import $ALLURE_OBJECT"
    const val EVERYTHING_IN_PARENTHESES = "\\([\\s\\S][^)]{1,}\\)"
    const val ALLURE_STEP = ALLURE_METHOD + "step"
    const val ALLURE_DYNAMIC = ALLURE_METHOD + "dynamic" + ANNOTATION_SEPARATOR
    const val ALLURE_DYNAMIC_TITLE = ALLURE_DYNAMIC + "title"
    const val ALLURE_DYNAMIC_DESCRIPTION = ALLURE_DYNAMIC + "description"
    const val ALLURE_DYNAMIC_DESCRIPTION_HTML = ALLURE_DYNAMIC + "description_html"
    const val ALLURE_DYNAMIC_LINK = ALLURE_DYNAMIC + "link" + EVERYTHING_IN_PARENTHESES
    const val ALLURE_DYNAMIC_ISSUE = ALLURE_DYNAMIC + "issue" + EVERYTHING_IN_PARENTHESES
    const val ALLURE_DYNAMIC_TESTCASES = ALLURE_DYNAMIC + "testcase" + EVERYTHING_IN_PARENTHESES
    const val ALLURE_DYNAMIC_TAG = ALLURE_DYNAMIC + "tag"
    const val ALLURE_DYNAMIC_LABEL = ALLURE_DYNAMIC + "label"
    const val ALLURE_DYNAMIC_ID = ALLURE_DYNAMIC + "id"
    const val ALLURE_DYNAMIC_EPIC = ALLURE_DYNAMIC + "epic"
    const val ALLURE_DYNAMIC_FEATURE = ALLURE_DYNAMIC + "feature"
    const val ALLURE_DYNAMIC_STORY = ALLURE_DYNAMIC + "story"
    const val ALLURE_DYNAMIC_PARENT_SUITE = ALLURE_DYNAMIC + "parent_suite"
    const val ALLURE_DYNAMIC_SUITE = ALLURE_DYNAMIC + "suite"
    const val ALLURE_DYNAMIC_SUB_SUITE = ALLURE_DYNAMIC + "sub_suite"
    const val ALLURE_DYNAMIC_PARAMETER = ALLURE_DYNAMIC + "parameter"
    const val ALLURE_DYNAMIC_ATTACHMENT_WRITE = ALLURE_METHOD + "attach" + EVERYTHING_IN_PARENTHESES
    const val ALLURE_DYNAMIC_ATTACHMENT_READ = ALLURE_METHOD + "attach" + ANNOTATION_SEPARATOR +
            "file" + EVERYTHING_IN_PARENTHESES
    const val VARIABLE = "[^'\",\\s)]+"
    const val VALUE = "'[^']*'|\"[^\"]*\""
    const val ASSIGNMENT = "\\s*=\\s*"

    const val LINK_URL_PARAMETER_NAME = "url"
    const val LINK_NAME_PARAMETER_NAME = "name"
    const val LINK_PARAMETER_WITHOUT_NAME = "(?!" + LINK_URL_PARAMETER_NAME + ASSIGNMENT + "|" +
            LINK_NAME_PARAMETER_NAME + ASSIGNMENT + ")"
    const val LINK_URL_PARAMETER = "(?:\\(\\s*" +
            "$LINK_PARAMETER_WITHOUT_NAME|(?<=$LINK_URL_PARAMETER_NAME)$ASSIGNMENT)" +
            "(?<$LINK_URL_PARAMETER_NAME>$VARIABLE|$VALUE)"
    const val LINK_NAME_PARAMETER = "(?:" +
            "\\(\\s*(?:$VARIABLE|$VALUE)\\s*,\\s*$LINK_PARAMETER_WITHOUT_NAME|" +
            "(?<=$LINK_NAME_PARAMETER_NAME)$ASSIGNMENT)" +
            "(?<$LINK_NAME_PARAMETER_NAME>$VARIABLE|$VALUE)"

    const val ATTACHMENT_BODY_PARAMETER_NAME = "body"
    const val ATTACHMENT_SOURCE_PARAMETER_NAME = "source"
    const val ATTACHMENT_NAME_PARAMETER_NAME = "name"
    const val ATTACHMENT_TYPE_PARAMETER_NAME = "attachment_type"
    const val ATTACHMENT_EXTENSION_PARAMETER_NAME = "extension"
    const val GENERAL_PARAMETER_WITHOUT_NAME = ATTACHMENT_NAME_PARAMETER_NAME + ASSIGNMENT + "|" +
            ATTACHMENT_TYPE_PARAMETER_NAME + ASSIGNMENT + "|" + ATTACHMENT_EXTENSION_PARAMETER_NAME + ASSIGNMENT
    const val ATTACHMENT_READ_PARAMETER_WITHOUT_NAME = "(?!" + ATTACHMENT_SOURCE_PARAMETER_NAME + ASSIGNMENT +
            "|" + GENERAL_PARAMETER_WITHOUT_NAME + ")"
    const val ATTACHMENT_WRITE_PARAMETER_WITHOUT_NAME = "(?!" + ATTACHMENT_BODY_PARAMETER_NAME + ASSIGNMENT +
            "|" + GENERAL_PARAMETER_WITHOUT_NAME + ")"
    const val ATTACHMENT_SOURCE_PARAMETER = "(?:\\(\\s*" +
            "$ATTACHMENT_READ_PARAMETER_WITHOUT_NAME|(?<=$ATTACHMENT_SOURCE_PARAMETER_NAME)$ASSIGNMENT)" +
            "(?<$ATTACHMENT_SOURCE_PARAMETER_NAME>$VARIABLE|$VALUE)"
    const val ATTACHMENT_BODY_PARAMETER = "(?:\\(\\s*" +
            "$ATTACHMENT_WRITE_PARAMETER_WITHOUT_NAME|(?<=$ATTACHMENT_BODY_PARAMETER_NAME)$ASSIGNMENT)" +
            "(?<$ATTACHMENT_BODY_PARAMETER_NAME>$VARIABLE|$VALUE)"
    const val ATTACHMENT_NAME_PARAMETER = "(?:" +
            "\\(\\s*(?:$VARIABLE|$VALUE)\\s*,\\s*$ATTACHMENT_READ_PARAMETER_WITHOUT_NAME|" +
            "(?<=$ATTACHMENT_NAME_PARAMETER_NAME)$ASSIGNMENT)" +
            "(?<$ATTACHMENT_NAME_PARAMETER_NAME>$VARIABLE|$VALUE)"

    const val PARAMETER_NAME_PARAMETER_NAME = "name"
    const val PARAMETER_VALUE_PARAMETER_NAME = "value"
    const val PARAMETER_PARAMETER_WITHOUT_NAME = "(?!" + PARAMETER_NAME_PARAMETER_NAME + ASSIGNMENT + "|" +
            PARAMETER_VALUE_PARAMETER_NAME + ASSIGNMENT + ")"
    const val PARAMETER_NAME_PARAMETER = "(?:\\(\\s*" +
            "$PARAMETER_PARAMETER_WITHOUT_NAME|(?<=$PARAMETER_NAME_PARAMETER_NAME)$ASSIGNMENT)" +
            "(?<$PARAMETER_NAME_PARAMETER_NAME>$VARIABLE|$VALUE)"
    const val PARAMETER_VALUE_PARAMETER = "(?:" +
            "\\(\\s*(?:$VARIABLE|$VALUE)\\s*,\\s*$PARAMETER_PARAMETER_WITHOUT_NAME|" +
            "(?<=$PARAMETER_VALUE_PARAMETER_NAME)$ASSIGNMENT)" +
            "(?<$PARAMETER_VALUE_PARAMETER_NAME>$VARIABLE|$VALUE)"

    const val TMS_LABELS = "Labels="
    const val TMS_LINKS = "Links="
    const val TMS_NAMESPACE = "NameSpace="
    const val TMS_CLASSNAME = "ClassName="
    const val TMS_DISPLAY_NAME = "DisplayName="

    const val TMS_OBJECT = "testit"
    const val METHOD_SEPARATOR_OBJECT = "."
    const val ANNOTATION_SEPARATOR_OBJECT = ","
    const val PARAMETERS_SEPARATOR_OBJECT = ", "
    const val TMS_METHOD_OBJECT = TMS_OBJECT + METHOD_SEPARATOR_OBJECT
    const val IMPORT_TMS_OBJECT = "import $TMS_OBJECT"
    const val TMS_STEP = TMS_METHOD_OBJECT + "step"
    const val TMS_ADD_DISPLAY_NAME = TMS_METHOD_OBJECT + "addDisplayName"
    const val TMS_ADD_NAMESPACE = TMS_METHOD_OBJECT + "addNameSpace"
    const val TMS_ADD_CLASSNAME = TMS_METHOD_OBJECT + "addClassName"
    const val TMS_ADD_DESCRIPTION = TMS_METHOD_OBJECT + "addDescription"
    const val TMS_ADD_LABELS = TMS_METHOD_OBJECT + "addLabels"
    const val TMS_ADD_LINKS = TMS_METHOD_OBJECT + "addLinks"
    const val TMS_ADD_PARAMETER = TMS_METHOD_OBJECT + "addParameter"
    const val TMS_ADD_ATTACHMENTS = TMS_METHOD_OBJECT + "addAttachments"
}