package ru.testit.management.parsers.regexps

object JUnitRegexp {
    const val ANNOTATION = "@"
    const val JUNIT_TEST_ANNOTATION = ANNOTATION + "Test"
    const val METHOD_ANNOTATIONS = "\\s+(?:[\\w\\s@()\"]*\\s+)?"
    const val TEST_METHOD = METHOD_ANNOTATIONS + JUNIT_TEST_ANNOTATION +
            METHOD_ANNOTATIONS + "\\w+\\s*\\([^)]*\\)\\s*(\\{(?:[^{}]|(?:\\{[^{}]*\\}))*\\})"

    const val ANNOTATION_SEPARATOR = "\\."
    const val EVERYTHING_IN_PARENTHESES = "\\([\\s\\S][^)]{1,}\\)"
    const val ALLURE_OBJECT = "Allure"
    const val IMPORT_ALLURE = "import io" + ANNOTATION_SEPARATOR + "qameta" + ANNOTATION_SEPARATOR + "allure"
    const val IMPORT_ALLURE_OBJECT = IMPORT_ALLURE + ANNOTATION_SEPARATOR + ALLURE_OBJECT
    const val IMPORT_JUPITER = "import org" + ANNOTATION_SEPARATOR + "junit" +
            ANNOTATION_SEPARATOR + "jupiter" + ANNOTATION_SEPARATOR + "api" + ANNOTATION_SEPARATOR
    const val IMPORT_JUPITER_DISPLAY_NAME = IMPORT_JUPITER + "DisplayName"
    const val IMPORT_ALLURE_DESCRIPTION = IMPORT_ALLURE + ANNOTATION_SEPARATOR + "Description"
    const val IMPORT_ALLURE_STEP = IMPORT_ALLURE + ANNOTATION_SEPARATOR + "Step"
    const val ALLURE_LINK = ANNOTATION + "Link" + EVERYTHING_IN_PARENTHESES
    const val ALLURE_ISSUE = ANNOTATION + "Issue" + EVERYTHING_IN_PARENTHESES
    const val ALLURE_TMS_LINK = ANNOTATION + "TmsLink" + EVERYTHING_IN_PARENTHESES
    const val ALLURE_OWNER = ANNOTATION + "Owner"
    const val ALLURE_ID = ANNOTATION + "AllureId"
    const val ALLURE_EPIC = ANNOTATION + "Epic"
    const val ALLURE_FEATURE = ANNOTATION + "Feature"
    const val ALLURE_STORY = ANNOTATION + "Story"
    const val JUPITER_TEST_WITH_PARAMETERS = ANNOTATION + "Test" + EVERYTHING_IN_PARENTHESES
    const val ALLURE_STEP_WITH_PARAMETERS = ANNOTATION + "Step" + EVERYTHING_IN_PARENTHESES
    const val ALLURE_METHOD = ALLURE_OBJECT + ANNOTATION_SEPARATOR
    const val ALLURE_DYNAMIC_DESCRIPTION = ALLURE_METHOD + "description"
    const val ALLURE_DYNAMIC_DESCRIPTION_HTML = ALLURE_OBJECT + "descriptionHtml"
    const val ALLURE_DYNAMIC_LINK = ALLURE_METHOD + "link" + EVERYTHING_IN_PARENTHESES
    const val ALLURE_DYNAMIC_ISSUE = ALLURE_METHOD + "issue" + EVERYTHING_IN_PARENTHESES
    const val ALLURE_DYNAMIC_TMS = ALLURE_METHOD + "tms" + EVERYTHING_IN_PARENTHESES
    const val ALLURE_DYNAMIC_LABEL = ALLURE_METHOD + "label" + EVERYTHING_IN_PARENTHESES
    const val ALLURE_DYNAMIC_EPIC = ALLURE_METHOD + "epic"
    const val ALLURE_DYNAMIC_FEATURE = ALLURE_METHOD + "feature"
    const val ALLURE_DYNAMIC_STORY = ALLURE_METHOD + "story"
    const val ALLURE_DYNAMIC_SUITE = ALLURE_METHOD + "suite"
    const val ALLURE_DYNAMIC_PARENT_SUITE_NAME = "parentSuite"
    const val ALLURE_DYNAMIC_SUB_SUITE_NAME = "subSuite"
    const val ALLURE_DYNAMIC_PARAMETER = ALLURE_METHOD + "parameter"
    const val ALLURE_DYNAMIC_ATTACHMENT_WRITE = ALLURE_METHOD + "addAttachment" + EVERYTHING_IN_PARENTHESES
    const val VARIABLE = "[^'\",\\s)]+"
    const val VALUE = "'[^']*'|\"[^\"]*\""
    const val ASSIGNMENT = "\\s*=\\s*"

    const val LINK_URL_PARAMETER_NAME = "url"
    const val LINK_NAME_PARAMETER_NAME = "name"
    const val LINK_PARAMETER_WITHOUT_NAME = "(?!" + LINK_URL_PARAMETER_NAME + ASSIGNMENT + "|" +
            LINK_NAME_PARAMETER_NAME + ASSIGNMENT + ")"
    const val LINK_URL_PARAMETER = "(?:\\(\\s*" +
            "$LINK_PARAMETER_WITHOUT_NAME|(?<=$LINK_URL_PARAMETER_NAME)$ASSIGNMENT)" +
            "(?<$LINK_URL_PARAMETER_NAME>$VARIABLE|$VALUE)"
    const val LINK_NAME_PARAMETER = "(?:" +
            "\\(\\s*(?:$VARIABLE|$VALUE)\\s*,\\s*$LINK_PARAMETER_WITHOUT_NAME|" +
            "(?<=$LINK_NAME_PARAMETER_NAME)$ASSIGNMENT)" +
            "(?<$LINK_NAME_PARAMETER_NAME>$VARIABLE|$VALUE)"

    const val ATTACHMENT_CONTENT_PARAMETER_NAME = "content"
    const val ATTACHMENT_SOURCE_PARAMETER_NAME = "source"
    const val ATTACHMENT_NAME_PARAMETER_NAME = "name"
    const val ATTACHMENT_TYPE_PARAMETER_NAME = "type"
    const val ATTACHMENT_EXTENSION_PARAMETER_NAME = "fileExtension"
    const val GENERAL_PARAMETER_WITHOUT_NAME = ATTACHMENT_NAME_PARAMETER_NAME + ASSIGNMENT + "|" +
            ATTACHMENT_TYPE_PARAMETER_NAME + ASSIGNMENT + "|" + ATTACHMENT_EXTENSION_PARAMETER_NAME + ASSIGNMENT
    const val ATTACHMENT_READ_PARAMETER_WITHOUT_NAME = "(?!" + ATTACHMENT_SOURCE_PARAMETER_NAME + ASSIGNMENT +
            "|" + GENERAL_PARAMETER_WITHOUT_NAME + ")"
    const val ATTACHMENT_WRITE_PARAMETER_WITHOUT_NAME = "(?!" + ATTACHMENT_CONTENT_PARAMETER_NAME + ASSIGNMENT +
            "|" + GENERAL_PARAMETER_WITHOUT_NAME + ")"
    const val ATTACHMENT_CONTENT_PARAMETER = "(?:\\(\\s*" +
            "$ATTACHMENT_WRITE_PARAMETER_WITHOUT_NAME|(?<=$ATTACHMENT_CONTENT_PARAMETER_NAME)$ASSIGNMENT)" +
            "(?<$ATTACHMENT_CONTENT_PARAMETER_NAME>$VARIABLE|$VALUE)"
    const val ATTACHMENT_NAME_PARAMETER = "(?:" +
            "\\(\\s*(?:$VARIABLE|$VALUE)\\s*,\\s*$ATTACHMENT_READ_PARAMETER_WITHOUT_NAME|" +
            "(?<=$ATTACHMENT_NAME_PARAMETER_NAME)$ASSIGNMENT)" +
            "(?<$ATTACHMENT_NAME_PARAMETER_NAME>$VARIABLE|$VALUE)"

    const val PARAMETER_NAME_PARAMETER_NAME = "name"
    const val PARAMETER_VALUE_PARAMETER_NAME = "value"
    const val PARAMETER_PARAMETER_WITHOUT_NAME = "(?!" + PARAMETER_NAME_PARAMETER_NAME + ASSIGNMENT + "|" +
            PARAMETER_VALUE_PARAMETER_NAME + ASSIGNMENT + ")"
    const val PARAMETER_NAME_PARAMETER = "(?:\\(\\s*" +
            "$PARAMETER_PARAMETER_WITHOUT_NAME|(?<=$PARAMETER_NAME_PARAMETER_NAME)$ASSIGNMENT)" +
            "(?<$PARAMETER_NAME_PARAMETER_NAME>$VARIABLE|$VALUE)"
    const val PARAMETER_VALUE_PARAMETER = "(?:" +
            "\\(\\s*(?:$VARIABLE|$VALUE)\\s*,\\s*$PARAMETER_PARAMETER_WITHOUT_NAME|" +
            "(?<=$PARAMETER_VALUE_PARAMETER_NAME)$ASSIGNMENT)" +
            "(?<$PARAMETER_VALUE_PARAMETER_NAME>$VARIABLE|$VALUE)"

    const val ANNOTATION_SEPARATOR_OBJECT = "."
    const val PARAMETERS_SEPARATOR_OBJECT = ", "
    const val TMS_OBJECT = "Adapter"
    const val IMPORT_TMS = "import ru" + ANNOTATION_SEPARATOR_OBJECT + "testit" + ANNOTATION_SEPARATOR_OBJECT
    const val IMPORT_TMS_ANNOTATIONS = IMPORT_TMS + "annotations" + ANNOTATION_SEPARATOR_OBJECT
    const val IMPORT_TMS_SERVICES = IMPORT_TMS + "services" + ANNOTATION_SEPARATOR_OBJECT
    const val TMS_DISPLAY_NAME_NAME = "DisplayName"
    const val TMS_STEP_NAME = "Step"
    const val IMPORT_TMS_DISPLAY_NAME = IMPORT_TMS_ANNOTATIONS + TMS_DISPLAY_NAME_NAME
    const val IMPORT_TMS_DESCRIPTION = IMPORT_TMS_ANNOTATIONS + "Description"
    const val IMPORT_TMS_STEP = IMPORT_TMS_ANNOTATIONS + TMS_STEP_NAME
    const val JUPITER_TEST = ANNOTATION + "Test"
    const val TMS_DISPLAY_NAME = ANNOTATION + TMS_DISPLAY_NAME_NAME
    const val TMS_STEP = ANNOTATION + TMS_STEP_NAME
    const val TMS_TITLE = ANNOTATION + "Title"
    const val TMS_LABELS = ANNOTATION + "Labels"
    const val TMS_LINK = ANNOTATION + "Link"
    const val IMPORT_TMS_OBJECT = IMPORT_TMS_SERVICES + TMS_OBJECT
    const val TMS_METHOD_OBJECT = TMS_OBJECT + ANNOTATION_SEPARATOR_OBJECT
    const val TMS_NAMESPACE = TMS_METHOD_OBJECT + "nameSpace"
    const val TMS_CLASSNAME = TMS_METHOD_OBJECT + "className"
    const val TMS_ADD_NAMESPACE = TMS_METHOD_OBJECT + "addNameSpace"
    const val TMS_ADD_CLASSNAME = TMS_METHOD_OBJECT + "addClassName"
    const val TMS_ADD_DESCRIPTION = TMS_METHOD_OBJECT + "addDescription"
    const val TMS_ADD_LABELS = TMS_METHOD_OBJECT + "addLabels"
    const val TMS_ADD_LINKS = TMS_METHOD_OBJECT + "addLinks"
    const val TMS_ADD_PARAMETER = TMS_METHOD_OBJECT + "addParameter"
    const val TMS_ADD_ATTACHMENTS = TMS_METHOD_OBJECT + "addAttachments"
}