[versions]
# libraries
jsoup = "1.17.2"
okhttp = "4.12.0"
slf4j = "2.0.13"
testit-api = "latest.release"
testit-common = "latest.release"

# plugins
kotlin = "2.0.0"
intellij = "1.17.3"

[libraries]
jsoup = { group = "org.jsoup", name = "jsoup", version.ref = "jsoup" }
okhttp = { group = "com.squareup.okhttp3", name = "okhttp", version.ref = "okhttp" }
slf4j = { group = "org.slf4j", name = "slf4j-simple", version.ref = "slf4j" }
testit-api = { group = "ru.testit", name = "testit-api-client", version.ref = "testit-api" }
testit-common = { group = "ru.testit", name = "testit-java-commons", version.ref = "testit-common" }

[plugins]
intellij = { id = "org.jetbrains.intellij", version.ref = "intellij" }
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }