[versions]
# libraries
jsoup = "1.17.2"
jakarta = "3.0.0"
slf4j = "2.0.13"
moshi = "1.15.1"
okhttp = "4.12.0"

# plugins
kotlin = "2.0.0"

[libraries]
jsoup = { group = "org.jsoup", name = "jsoup", version.ref = "jsoup" }
jakarta = { group = "jakarta.ws.rs", name = "jakarta.ws.rs-api", version.ref = "jakarta" }

slf4j = { group = "org.slf4j", name = "slf4j-simple", version.ref = "slf4j" }
moshi = { group = "com.squareup.moshi", name = "moshi", version.ref = "moshi" }
moshi-kotlin = { group = "com.squareup.moshi", name = "moshi-kotlin", version.ref = "moshi" }
okhttp = { group = "com.squareup.okhttp3", name = "okhttp", version.ref = "okhttp" }

[plugins]
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
