/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ru.testit.kotlin.adaptersapi.models

import ru.testit.kotlin.adaptersapi.models.ParameterIterationModel

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param parameters 
 * @param id Iteration identifier, must be empty for new or changed iteration
 */


data class AssignIterationApiModel (

    @Json(name = "parameters")
    val parameters: kotlin.collections.List<ParameterIterationModel>,

    /* Iteration identifier, must be empty for new or changed iteration */
    @Json(name = "id")
    val id: java.util.UUID

) {


}

