/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ru.testit.kotlin.adaptersapi.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param fileId Unique ID of the attachment file
 * @param type MIME type of the attachment
 * @param propertySize Size in bytes of the attachment file
 * @param createdDate Creation date of the attachment
 * @param createdById Unique ID of the attachment creator
 * @param name Name of the attachment file
 * @param id Unique ID of the attachment
 * @param modifiedDate Last modification date of the attachment
 * @param modifiedById Unique ID of the attachment last editor
 */


data class AttachmentModel (

    /* Unique ID of the attachment file */
    @Json(name = "fileId")
    val fileId: kotlin.String,

    /* MIME type of the attachment */
    @Json(name = "type")
    val type: kotlin.String,

    /* Size in bytes of the attachment file */
    @Json(name = "size")
    val propertySize: kotlin.Float,

    /* Creation date of the attachment */
    @Json(name = "createdDate")
    val createdDate: java.time.OffsetDateTime,

    /* Unique ID of the attachment creator */
    @Json(name = "createdById")
    val createdById: java.util.UUID,

    /* Name of the attachment file */
    @Json(name = "name")
    val name: kotlin.String,

    /* Unique ID of the attachment */
    @Json(name = "id")
    val id: java.util.UUID,

    /* Last modification date of the attachment */
    @Json(name = "modifiedDate")
    val modifiedDate: java.time.OffsetDateTime? = null,

    /* Unique ID of the attachment last editor */
    @Json(name = "modifiedById")
    val modifiedById: java.util.UUID? = null

) {


}

