/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ru.testit.kotlin.adaptersapi.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id Unique ID of the attachment
 * @param fileId Unique ID of the attachment file
 * @param type MIME type of the attachment
 * @param propertySize Size in bytes of the attachment file
 * @param name Name of the attachment file
 */


data class AttachmentApiResult (

    /* Unique ID of the attachment */
    @Json(name = "id")
    val id: java.util.UUID,

    /* Unique ID of the attachment file */
    @Json(name = "fileId")
    val fileId: kotlin.String,

    /* MIME type of the attachment */
    @Json(name = "type")
    val type: kotlin.String,

    /* Size in bytes of the attachment file */
    @Json(name = "size")
    val propertySize: kotlin.Float,

    /* Name of the attachment file */
    @Json(name = "name")
    val name: kotlin.String

) {


}

