/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ru.testit.kotlin.adaptersapi.models

import ru.testit.kotlin.adaptersapi.models.AutoTestStepApiResult
import ru.testit.kotlin.adaptersapi.models.LabelApiResult
import ru.testit.kotlin.adaptersapi.models.LayerApiResult
import ru.testit.kotlin.adaptersapi.models.LinkApiResult

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id 
 * @param projectId 
 * @param name 
 * @param isFlaky 
 * @param globalId 
 * @param externalId 
 * @param namespace 
 * @param classname 
 * @param steps 
 * @param setup 
 * @param teardown 
 * @param title 
 * @param description 
 * @param externalKey 
 * @param layer Model of auto test layer for use in responses.
 * @param links 
 * @param labels 
 * @param tags 
 */


data class AutoTestApiResult (

    @Json(name = "id")
    val id: java.util.UUID,

    @Json(name = "projectId")
    val projectId: java.util.UUID,

    @Json(name = "name")
    val name: kotlin.String,

    @Json(name = "isFlaky")
    val isFlaky: kotlin.Boolean,

    @Json(name = "globalId")
    val globalId: kotlin.Long,

    @Json(name = "externalId")
    val externalId: kotlin.String? = null,

    @Json(name = "namespace")
    val namespace: kotlin.String? = null,

    @Json(name = "classname")
    val classname: kotlin.String? = null,

    @Json(name = "steps")
    val steps: kotlin.collections.List<AutoTestStepApiResult>? = null,

    @Json(name = "setup")
    val setup: kotlin.collections.List<AutoTestStepApiResult>? = null,

    @Json(name = "teardown")
    val teardown: kotlin.collections.List<AutoTestStepApiResult>? = null,

    @Json(name = "title")
    val title: kotlin.String? = null,

    @Json(name = "description")
    val description: kotlin.String? = null,

    @Json(name = "externalKey")
    val externalKey: kotlin.String? = null,

    /* Model of auto test layer for use in responses. */
    @Json(name = "layer")
    val layer: LayerApiResult? = null,

    @Json(name = "links")
    val links: kotlin.collections.List<LinkApiResult>? = null,

    @Json(name = "labels")
    val labels: kotlin.collections.List<LabelApiResult>? = null,

    @Json(name = "tags")
    val tags: kotlin.collections.List<kotlin.String>? = null

) {


}

