/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ru.testit.kotlin.adaptersapi.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param projectIds Specifies an autotest projects IDs to search for
 * @param externalIds Specifies an autotest external IDs to search for
 * @param globalIds Specifies an autotest global IDs to search for
 * @param name Specifies an autotest name to search for
 * @param isFlaky Specifies an autotest flaky status to search for
 * @param isDeleted Specifies an autotest deleted status to search for
 * @param namespace Specifies an autotest namespace to search for
 * @param className Specifies an autotest class name to search for
 * @param externalKey Specifies an autotest external key to search for
 * @param tags Specifies an autotest tags to search for
 * @param excludeTags Specifies an autotest tags to exclude
 */


data class AutoTestFilterApiModel (

    /* Specifies an autotest projects IDs to search for */
    @Json(name = "projectIds")
    val projectIds: kotlin.collections.Set<java.util.UUID>? = null,

    /* Specifies an autotest external IDs to search for */
    @Json(name = "externalIds")
    val externalIds: kotlin.collections.Set<kotlin.String>? = null,

    /* Specifies an autotest global IDs to search for */
    @Json(name = "globalIds")
    val globalIds: kotlin.collections.Set<kotlin.Long>? = null,

    /* Specifies an autotest name to search for */
    @Json(name = "name")
    val name: kotlin.String? = null,

    /* Specifies an autotest flaky status to search for */
    @Json(name = "isFlaky")
    val isFlaky: kotlin.Boolean? = null,

    /* Specifies an autotest deleted status to search for */
    @Json(name = "isDeleted")
    val isDeleted: kotlin.Boolean? = null,

    /* Specifies an autotest namespace to search for */
    @Json(name = "namespace")
    val namespace: kotlin.String? = null,

    /* Specifies an autotest class name to search for */
    @Json(name = "className")
    val className: kotlin.String? = null,

    /* Specifies an autotest external key to search for */
    @Json(name = "externalKey")
    val externalKey: kotlin.String? = null,

    /* Specifies an autotest tags to search for */
    @Json(name = "tags")
    val tags: kotlin.collections.Set<kotlin.String>? = null,

    /* Specifies an autotest tags to exclude */
    @Json(name = "excludeTags")
    val excludeTags: kotlin.collections.Set<kotlin.String>? = null

) {


}

