/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ru.testit.kotlin.adaptersapi.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id WorkItem unique internal identifier
 * @param globalId WorkItem Global unique identifier
 */


data class AutoTestWorkItemIdentifierApiResult (

    /* WorkItem unique internal identifier */
    @Json(name = "id")
    val id: java.util.UUID,

    /* WorkItem Global unique identifier */
    @Json(name = "globalId")
    val globalId: kotlin.Long

) {


}

