/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ru.testit.kotlin.adaptersapi.models

import ru.testit.kotlin.adaptersapi.models.AutoTestStepApiModel
import ru.testit.kotlin.adaptersapi.models.LabelApiModel
import ru.testit.kotlin.adaptersapi.models.LayerApiModel
import ru.testit.kotlin.adaptersapi.models.LinkUpdateApiModel

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param projectId Unique ID of the autotest project
 * @param externalId External ID of the autotest
 * @param name Name of the autotest
 * @param resetLayer Indicates if the autotest layer should be reset.
 * @param id Autotest unique internal identifier
 * @param externalKey External key of the autotest
 * @param namespace Name of the autotest namespace
 * @param classname Name of the autotest class
 * @param title Name of the autotest in autotest's card
 * @param description Description of the autotest in autotest's card
 * @param isFlaky Indicates if the autotest is marked as flaky
 * @param layer Layer of the autotest. Assigns layer by rules if omitted.
 * @param steps Collection of the autotest steps
 * @param setup Collection of the autotest setup steps
 * @param teardown Collection of the autotest teardown steps
 * @param labels Collection of the autotest labels
 * @param links Collection of the autotest links
 * @param tags Collection of the autotest tags
 */


data class AutoTestUpdateApiModel (

    /* Unique ID of the autotest project */
    @Json(name = "projectId")
    val projectId: java.util.UUID,

    /* External ID of the autotest */
    @Json(name = "externalId")
    val externalId: kotlin.String,

    /* Name of the autotest */
    @Json(name = "name")
    val name: kotlin.String,

    /* Indicates if the autotest layer should be reset. */
    @Json(name = "resetLayer")
    val resetLayer: kotlin.Boolean,

    /* Autotest unique internal identifier */
    @Json(name = "id")
    val id: java.util.UUID? = null,

    /* External key of the autotest */
    @Json(name = "externalKey")
    val externalKey: kotlin.String? = null,

    /* Name of the autotest namespace */
    @Json(name = "namespace")
    val namespace: kotlin.String? = null,

    /* Name of the autotest class */
    @Json(name = "classname")
    val classname: kotlin.String? = null,

    /* Name of the autotest in autotest's card */
    @Json(name = "title")
    val title: kotlin.String? = null,

    /* Description of the autotest in autotest's card */
    @Json(name = "description")
    val description: kotlin.String? = null,

    /* Indicates if the autotest is marked as flaky */
    @Json(name = "isFlaky")
    val isFlaky: kotlin.Boolean? = null,

    /* Layer of the autotest. Assigns layer by rules if omitted. */
    @Json(name = "layer")
    val layer: LayerApiModel? = null,

    /* Collection of the autotest steps */
    @Json(name = "steps")
    val steps: kotlin.collections.List<AutoTestStepApiModel>? = null,

    /* Collection of the autotest setup steps */
    @Json(name = "setup")
    val setup: kotlin.collections.List<AutoTestStepApiModel>? = null,

    /* Collection of the autotest teardown steps */
    @Json(name = "teardown")
    val teardown: kotlin.collections.List<AutoTestStepApiModel>? = null,

    /* Collection of the autotest labels */
    @Json(name = "labels")
    val labels: kotlin.collections.List<LabelApiModel>? = null,

    /* Collection of the autotest links */
    @Json(name = "links")
    val links: kotlin.collections.List<LinkUpdateApiModel>? = null,

    /* Collection of the autotest tags */
    @Json(name = "tags")
    val tags: kotlin.collections.List<kotlin.String>? = null

) {


}

