/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ru.testit.kotlin.adaptersapi.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param includeSteps If autotest steps will be included
 * @param includeLinks If autotest links will be included
 * @param includeLabels If autotest labels will be included
 */


data class AutoTestSearchIncludeApiModel (

    /* If autotest steps will be included */
    @Json(name = "includeSteps")
    val includeSteps: kotlin.Boolean? = null,

    /* If autotest links will be included */
    @Json(name = "includeLinks")
    val includeLinks: kotlin.Boolean? = null,

    /* If autotest labels will be included */
    @Json(name = "includeLabels")
    val includeLabels: kotlin.Boolean? = null

) {


}

