/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ru.testit.kotlin.adaptersapi.models

import ru.testit.kotlin.adaptersapi.models.FailureCategoryModel

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param failureCategory 
 * @param name 
 */


data class AutoTestResultReasonShort (

    @Json(name = "failureCategory")
    val failureCategory: FailureCategoryModel,

    @Json(name = "name")
    val name: kotlin.String

) {


}

