/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ru.testit.kotlin.adaptersapi.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param title Step name.
 * @param description Detailed step description. It appears when the step is unfolded.
 * @param steps Includes a nested step inside another step. The maximum nesting level is 15.
 */


data class AutoTestStepApiModel (

    /* Step name. */
    @Json(name = "title")
    val title: kotlin.String,

    /* Detailed step description. It appears when the step is unfolded. */
    @Json(name = "description")
    val description: kotlin.String? = null,

    /* Includes a nested step inside another step. The maximum nesting level is 15. */
    @Json(name = "steps")
    val steps: kotlin.collections.List<AutoTestStepApiModel>? = null

) {


}

