/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ru.testit.kotlin.adaptersapi.models

import ru.testit.kotlin.adaptersapi.models.AutoTestFilterApiModel
import ru.testit.kotlin.adaptersapi.models.AutoTestSearchIncludeApiModel

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param filter Object containing different filters to adjust search
 * @param includes Object specifying data to be included
 */


data class AutoTestSearchApiModel (

    /* Object containing different filters to adjust search */
    @Json(name = "filter")
    val filter: AutoTestFilterApiModel? = null,

    /* Object specifying data to be included */
    @Json(name = "includes")
    val includes: AutoTestSearchIncludeApiModel? = null

) {


}

