/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ru.testit.kotlin.adaptersapi.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param projectId This property is used to link configuration with project
 * @param isDefault 
 * @param createdDate 
 * @param createdById 
 * @param globalId 
 * @param id Unique ID of the entity
 * @param isDeleted Indicates if the entity is deleted
 * @param description 
 * @param parameters 
 * @param name 
 * @param modifiedDate 
 * @param modifiedById 
 */


data class ConfigurationModel (

    /* This property is used to link configuration with project */
    @Json(name = "projectId")
    val projectId: java.util.UUID,

    @Json(name = "isDefault")
    val isDefault: kotlin.Boolean,

    @Json(name = "createdDate")
    val createdDate: java.time.OffsetDateTime,

    @Json(name = "createdById")
    val createdById: java.util.UUID,

    @Json(name = "globalId")
    val globalId: kotlin.Long,

    /* Unique ID of the entity */
    @Json(name = "id")
    val id: java.util.UUID,

    /* Indicates if the entity is deleted */
    @Json(name = "isDeleted")
    val isDeleted: kotlin.Boolean,

    @Json(name = "description")
    val description: kotlin.String? = null,

    @Json(name = "parameters")
    val parameters: kotlin.collections.Map<kotlin.String, kotlin.String>? = null,

    @Json(name = "name")
    val name: kotlin.String? = null,

    @Json(name = "modifiedDate")
    val modifiedDate: java.time.OffsetDateTime? = null,

    @Json(name = "modifiedById")
    val modifiedById: java.util.UUID? = null

) {


}

