/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ru.testit.kotlin.adaptersapi.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param projectIds Collection of identifiers of projects from which configurations will be taken
 * @param name Filter to search by name (case-insensitive, partial match)
 * @param isDeleted Is configurations deleted or existing
 * @param globalIds Collection of global (integer) identifiers to filter configurations
 */


data class ConfigurationFilterModel (

    /* Collection of identifiers of projects from which configurations will be taken */
    @Json(name = "projectIds")
    val projectIds: kotlin.collections.Set<java.util.UUID>? = null,

    /* Filter to search by name (case-insensitive, partial match) */
    @Json(name = "name")
    val name: kotlin.String? = null,

    /* Is configurations deleted or existing */
    @Json(name = "isDeleted")
    val isDeleted: kotlin.Boolean? = null,

    /* Collection of global (integer) identifiers to filter configurations */
    @Json(name = "globalIds")
    val globalIds: kotlin.collections.Set<kotlin.Long>? = null

) {


}

