/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ru.testit.kotlin.adaptersapi.models

import ru.testit.kotlin.adaptersapi.models.AssignAttachmentApiModel
import ru.testit.kotlin.adaptersapi.models.AssignIterationApiModel
import ru.testit.kotlin.adaptersapi.models.AutoTestIdModel
import ru.testit.kotlin.adaptersapi.models.CreateLinkApiModel
import ru.testit.kotlin.adaptersapi.models.CreateStepApiModel
import ru.testit.kotlin.adaptersapi.models.TagModel
import ru.testit.kotlin.adaptersapi.models.WorkItemEntityTypeApiModel
import ru.testit.kotlin.adaptersapi.models.WorkItemParameterKeyApiModel
import ru.testit.kotlin.adaptersapi.models.WorkItemPriorityApiModel
import ru.testit.kotlin.adaptersapi.models.WorkItemStateApiModel

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param projectId Unique identifier of the project
 * @param name Name of the work item
 * @param entityTypeName Type of entity associated with this work item
 * @param duration Duration of the work item in milliseconds
 * @param state Current state of the work item
 * @param priority Priority level assigned to the work item
 * @param sectionId Unique identifier of the section within a project
 * @param description Description of the work item
 * @param attributes Set of custom attributes associated with the work item
 * @param tags Set of tags applied to the work item
 * @param preconditionSteps Set of precondition steps that must be executed before the main steps
 * @param steps Set of main steps or actions defined for the work item
 * @param postconditionSteps Set of postcondition steps that are executed after completing the main steps
 * @param iterations Set of iterations associated with the work item
 * @param autoTests Set of automated tests linked to the work item
 * @param attachments Set of files attached to the work item
 * @param links Set of links related to the work item
 * @param parameters Set of parameter keys associated with the work item
 */


data class CreateWorkItemApiModel (

    /* Unique identifier of the project */
    @Json(name = "projectId")
    val projectId: java.util.UUID,

    /* Name of the work item */
    @Json(name = "name")
    val name: kotlin.String,

    /* Type of entity associated with this work item */
    @Json(name = "entityTypeName")
    val entityTypeName: WorkItemEntityTypeApiModel,

    /* Duration of the work item in milliseconds */
    @Json(name = "duration")
    val duration: kotlin.Long,

    /* Current state of the work item */
    @Json(name = "state")
    val state: WorkItemStateApiModel,

    /* Priority level assigned to the work item */
    @Json(name = "priority")
    val priority: WorkItemPriorityApiModel,

    /* Unique identifier of the section within a project */
    @Json(name = "sectionId")
    val sectionId: java.util.UUID? = null,

    /* Description of the work item */
    @Json(name = "description")
    val description: kotlin.String? = null,

    /* Set of custom attributes associated with the work item */
    @Json(name = "attributes")
    val attributes: kotlin.collections.Map<kotlin.String, kotlin.Any>? = null,

    /* Set of tags applied to the work item */
    @Json(name = "tags")
    val tags: kotlin.collections.List<TagModel>? = null,

    /* Set of precondition steps that must be executed before the main steps */
    @Json(name = "preconditionSteps")
    val preconditionSteps: kotlin.collections.List<CreateStepApiModel>? = null,

    /* Set of main steps or actions defined for the work item */
    @Json(name = "steps")
    val steps: kotlin.collections.List<CreateStepApiModel>? = null,

    /* Set of postcondition steps that are executed after completing the main steps */
    @Json(name = "postconditionSteps")
    val postconditionSteps: kotlin.collections.List<CreateStepApiModel>? = null,

    /* Set of iterations associated with the work item */
    @Json(name = "iterations")
    val iterations: kotlin.collections.List<AssignIterationApiModel>? = null,

    /* Set of automated tests linked to the work item */
    @Json(name = "autoTests")
    val autoTests: kotlin.collections.List<AutoTestIdModel>? = null,

    /* Set of files attached to the work item */
    @Json(name = "attachments")
    val attachments: kotlin.collections.List<AssignAttachmentApiModel>? = null,

    /* Set of links related to the work item */
    @Json(name = "links")
    val links: kotlin.collections.List<CreateLinkApiModel>? = null,

    /* Set of parameter keys associated with the work item */
    @Json(name = "parameters")
    val parameters: kotlin.collections.List<WorkItemParameterKeyApiModel>? = null

) {


}

