/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ru.testit.kotlin.adaptersapi.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param name Key of the parameter
 * @param `value` Value of the parameter
 * @param projectIds List of projects where parameter should be available
 */


data class CreateParameterApiModel (

    /* Key of the parameter */
    @Json(name = "name")
    val name: kotlin.String,

    /* Value of the parameter */
    @Json(name = "value")
    val `value`: kotlin.String,

    /* List of projects where parameter should be available */
    @Json(name = "projectIds")
    val projectIds: kotlin.collections.List<java.util.UUID>? = null

) {


}

