/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ru.testit.kotlin.adaptersapi.models

import ru.testit.kotlin.adaptersapi.models.AssignAttachmentApiModel
import ru.testit.kotlin.adaptersapi.models.CreateLinkApiModel

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param projectId Project unique identifier              This property is to link test run with a project
 * @param name Test run name
 * @param description Test run description
 * @param launchSource Test run launch source
 * @param attachments Collection of attachments to relate to the test run
 * @param links Collection of links to relate to the test run
 * @param tags Collection of tags to assign to the test run
 */


data class CreateEmptyTestRunApiModel (

    /* Project unique identifier              This property is to link test run with a project */
    @Json(name = "projectId")
    val projectId: java.util.UUID,

    /* Test run name */
    @Json(name = "name")
    val name: kotlin.String? = null,

    /* Test run description */
    @Json(name = "description")
    val description: kotlin.String? = null,

    /* Test run launch source */
    @Json(name = "launchSource")
    val launchSource: kotlin.String? = null,

    /* Collection of attachments to relate to the test run */
    @Json(name = "attachments")
    val attachments: kotlin.collections.List<AssignAttachmentApiModel>? = null,

    /* Collection of links to relate to the test run */
    @Json(name = "links")
    val links: kotlin.collections.List<CreateLinkApiModel>? = null,

    /* Collection of tags to assign to the test run */
    @Json(name = "tags")
    val tags: kotlin.collections.List<kotlin.String>? = null

) {


}

