/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ru.testit.kotlin.adaptersapi.models

import ru.testit.kotlin.adaptersapi.models.CustomAttributeOptionApiResult
import ru.testit.kotlin.adaptersapi.models.CustomAttributeType
import ru.testit.kotlin.adaptersapi.models.ProjectShortestApiResult

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param workItemUsage Projects where attribute is used in work items
 * @param testPlanUsage Projects where attribute is used in test plans
 * @param id Unique ID of the attribute
 * @param options Collection of the attribute options   Available for attributes of type `options` and `multiple options` only
 * @param type Type of the attribute
 * @param isDeleted Indicates if the attribute is deleted
 * @param name Name of the attribute
 * @param isEnabled Indicates if the attribute is enabled
 * @param isRequired Indicates if the attribute value is mandatory to specify
 * @param isGlobal Indicates if the attribute is available across all projects
 * @param isReadOnly Indicates if the attribute is read-only
 * @param isSystem Indicates if the attribute is system
 * @param targets Collection of the attribute targets   Defines where the attribute can be used (e.g., TestCases, AutoTestCases, TestPlans)
 * @param code Optional code identifier for the attribute
 */


data class CustomAttributeSearchApiResult (

    /* Projects where attribute is used in work items */
    @Json(name = "workItemUsage")
    val workItemUsage: kotlin.collections.List<ProjectShortestApiResult>,

    /* Projects where attribute is used in test plans */
    @Json(name = "testPlanUsage")
    val testPlanUsage: kotlin.collections.List<ProjectShortestApiResult>,

    /* Unique ID of the attribute */
    @Json(name = "id")
    val id: java.util.UUID,

    /* Collection of the attribute options   Available for attributes of type `options` and `multiple options` only */
    @Json(name = "options")
    val options: kotlin.collections.List<CustomAttributeOptionApiResult>,

    /* Type of the attribute */
    @Json(name = "type")
    val type: CustomAttributeType,

    /* Indicates if the attribute is deleted */
    @Json(name = "isDeleted")
    val isDeleted: kotlin.Boolean,

    /* Name of the attribute */
    @Json(name = "name")
    val name: kotlin.String,

    /* Indicates if the attribute is enabled */
    @Json(name = "isEnabled")
    val isEnabled: kotlin.Boolean,

    /* Indicates if the attribute value is mandatory to specify */
    @Json(name = "isRequired")
    val isRequired: kotlin.Boolean,

    /* Indicates if the attribute is available across all projects */
    @Json(name = "isGlobal")
    val isGlobal: kotlin.Boolean,

    /* Indicates if the attribute is read-only */
    @Json(name = "isReadOnly")
    val isReadOnly: kotlin.Boolean,

    /* Indicates if the attribute is system */
    @Json(name = "isSystem")
    val isSystem: kotlin.Boolean,

    /* Collection of the attribute targets   Defines where the attribute can be used (e.g., TestCases, AutoTestCases, TestPlans) */
    @Json(name = "targets")
    val targets: kotlin.collections.List<kotlin.String>,

    /* Optional code identifier for the attribute */
    @Json(name = "code")
    val code: kotlin.String? = null

) {


}

