/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ru.testit.kotlin.adaptersapi.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * Values: string,datetime,options,user,multipleOptions,checkbox
 */

@JsonClass(generateAdapter = false)
enum class CustomAttributeType(val value: kotlin.String) {

    @Json(name = "string")
    string("string"),

    @Json(name = "datetime")
    datetime("datetime"),

    @Json(name = "options")
    options("options"),

    @Json(name = "user")
    user("user"),

    @Json(name = "multipleOptions")
    multipleOptions("multipleOptions"),

    @Json(name = "checkbox")
    checkbox("checkbox");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is CustomAttributeType) "$data" else null

        /**
         * Returns a valid [CustomAttributeType] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): CustomAttributeType? = data?.let {
          val normalizedData = "$it".lowercase()
          values().firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

