/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ru.testit.kotlin.adaptersapi.models

import ru.testit.kotlin.adaptersapi.models.CustomAttributeApiResult
import ru.testit.kotlin.adaptersapi.models.WorkflowApiResult

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param workflow ID of the workflow used in project
 * @param id Unique ID of the project
 * @param name Name of the project
 * @param isFavorite Indicates if the project is marked as favorite
 * @param isDeleted Indicates if the project is deleted
 * @param globalId Global ID of the project
 * @param workflowId ID of the workflow used in project
 * @param attributesScheme Collection of the project attributes
 * @param description Description of the project
 */


data class DetailedProjectApiResult (

    /* ID of the workflow used in project */
    @Json(name = "workflow")
    val workflow: WorkflowApiResult,

    /* Unique ID of the project */
    @Json(name = "id")
    val id: java.util.UUID,

    /* Name of the project */
    @Json(name = "name")
    val name: kotlin.String,

    /* Indicates if the project is marked as favorite */
    @Json(name = "isFavorite")
    val isFavorite: kotlin.Boolean,

    /* Indicates if the project is deleted */
    @Json(name = "isDeleted")
    val isDeleted: kotlin.Boolean,

    /* Global ID of the project */
    @Json(name = "globalId")
    val globalId: kotlin.Long,

    /* ID of the workflow used in project */
    @Json(name = "workflowId")
    val workflowId: java.util.UUID,

    /* Collection of the project attributes */
    @Json(name = "attributesScheme")
    val attributesScheme: kotlin.collections.List<CustomAttributeApiResult>? = null,

    /* Description of the project */
    @Json(name = "description")
    val description: kotlin.String? = null

) {


}

