/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ru.testit.kotlin.adaptersapi.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param include 
 * @param exclude 
 */


data class GuidExtractionModel (

    @Json(name = "include")
    val include: kotlin.collections.List<java.util.UUID>? = null,

    @Json(name = "exclude")
    val exclude: kotlin.collections.List<java.util.UUID>? = null

) {


}

