/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ru.testit.kotlin.adaptersapi.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param from 
 * @param to 
 */


data class Int64RangeSelectorModel (

    @Json(name = "from")
    val from: kotlin.Long? = null,

    @Json(name = "to")
    val to: kotlin.Long? = null

) {


}

