/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ru.testit.kotlin.adaptersapi.models

import ru.testit.kotlin.adaptersapi.models.ParameterShortApiResult

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id 
 * @param parameters 
 */


data class IterationApiResult (

    @Json(name = "id")
    val id: java.util.UUID,

    @Json(name = "parameters")
    val parameters: kotlin.collections.List<ParameterShortApiResult>? = null

) {


}

