/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ru.testit.kotlin.adaptersapi.models

import ru.testit.kotlin.adaptersapi.models.LayerSource

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Model of auto test layer for use in responses.
 *
 * @param name Name of the test pyramid layer.
 * @param source Source of the test pyramid layer.
 */


data class LayerApiResult (

    /* Name of the test pyramid layer. */
    @Json(name = "name")
    val name: kotlin.String,

    /* Source of the test pyramid layer. */
    @Json(name = "source")
    val source: LayerSource

) {


}

