/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ru.testit.kotlin.adaptersapi.models

import ru.testit.kotlin.adaptersapi.models.LinkType

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param url Address can be specified without protocol, but necessarily with the domain.
 * @param type Specifies the type of the link.
 * @param title Link name.
 * @param description Link description.
 */


data class LinkCreateApiModel (

    /* Address can be specified without protocol, but necessarily with the domain. */
    @Json(name = "url")
    val url: kotlin.String,

    /* Specifies the type of the link. */
    @Json(name = "type")
    val type: LinkType,

    /* Link name. */
    @Json(name = "title")
    val title: kotlin.String? = null,

    /* Link description. */
    @Json(name = "description")
    val description: kotlin.String? = null

) {


}

