/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ru.testit.kotlin.adaptersapi.models

import ru.testit.kotlin.adaptersapi.models.GuidExtractionModel

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param testResultIds Set of extracted test result IDs
 */


data class ManualRerunTestResultApiModel (

    /* Set of extracted test result IDs */
    @Json(name = "testResultIds")
    val testResultIds: GuidExtractionModel? = null

) {


}

