/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ru.testit.kotlin.adaptersapi.models

import ru.testit.kotlin.adaptersapi.models.ManualRerunTestResultApiModel
import ru.testit.kotlin.adaptersapi.models.TestResultsFilterApiModel

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param filter Test results filter.
 * @param extractionModel Test results extraction model.
 * @param webhookIds Webhook ids to rerun.
 */


data class ManualRerunSelectTestResultsApiModel (

    /* Test results filter. */
    @Json(name = "filter")
    val filter: TestResultsFilterApiModel? = null,

    /* Test results extraction model. */
    @Json(name = "extractionModel")
    val extractionModel: ManualRerunTestResultApiModel? = null,

    /* Webhook ids to rerun. */
    @Json(name = "webhookIds")
    val webhookIds: kotlin.collections.List<java.util.UUID>? = null

) {


}

