/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ru.testit.kotlin.adaptersapi.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id 
 * @param sharedStepId 
 */


data class ParameterIterationModel (

    @Json(name = "id")
    val id: java.util.UUID,

    @Json(name = "sharedStepId")
    val sharedStepId: java.util.UUID? = null

) {


}

