/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ru.testit.kotlin.adaptersapi.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id 
 * @param parameterKeyId 
 * @param `value` Value of the parameter
 * @param name Key of the parameter
 */


data class ParameterShortApiResult (

    @Json(name = "id")
    val id: java.util.UUID,

    @Json(name = "parameterKeyId")
    val parameterKeyId: java.util.UUID,

    /* Value of the parameter */
    @Json(name = "value")
    val `value`: kotlin.String,

    /* Key of the parameter */
    @Json(name = "name")
    val name: kotlin.String

) {


}

