/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ru.testit.kotlin.adaptersapi.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id 
 * @param parameterKeyId 
 * @param name 
 * @param `value` 
 * @param isDeleted 
 * @param projectIds 
 */


data class ParameterApiResult (

    @Json(name = "id")
    val id: java.util.UUID,

    @Json(name = "parameterKeyId")
    val parameterKeyId: java.util.UUID,

    @Json(name = "name")
    val name: kotlin.String,

    @Json(name = "value")
    val `value`: kotlin.String,

    @Json(name = "isDeleted")
    val isDeleted: kotlin.Boolean,

    @Json(name = "projectIds")
    val projectIds: kotlin.collections.List<java.util.UUID>

) {


}

