/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ru.testit.kotlin.adaptersapi.models

import ru.testit.kotlin.adaptersapi.models.DateTimeRangeSelectorModel
import ru.testit.kotlin.adaptersapi.models.Int64RangeSelectorModel
import ru.testit.kotlin.adaptersapi.models.ProjectTypeModel

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param name Specifies a project name to search for
 * @param isFavorite Specifies a project favorite status to search for
 * @param isDeleted Specifies a project deleted status to search for
 * @param testCasesCount Specifies a project range of test cases count to search for
 * @param checklistsCount Specifies a project range of checklists count to search for
 * @param sharedStepsCount Specifies a project range of shared steps count to search for
 * @param autotestsCount Specifies a project range of autotests count to search for
 * @param globalIds Specifies a project global IDs to search for
 * @param createdDate Specifies a project range of creation date to search for
 * @param createdByIds Specifies an autotest creator IDs to search for
 * @param types Collection of project types to search for
 */


data class ProjectsFilterModel (

    /* Specifies a project name to search for */
    @Json(name = "name")
    val name: kotlin.String? = null,

    /* Specifies a project favorite status to search for */
    @Json(name = "isFavorite")
    val isFavorite: kotlin.Boolean? = null,

    /* Specifies a project deleted status to search for */
    @Json(name = "isDeleted")
    val isDeleted: kotlin.Boolean? = null,

    /* Specifies a project range of test cases count to search for */
    @Json(name = "testCasesCount")
    val testCasesCount: Int64RangeSelectorModel? = null,

    /* Specifies a project range of checklists count to search for */
    @Json(name = "checklistsCount")
    val checklistsCount: Int64RangeSelectorModel? = null,

    /* Specifies a project range of shared steps count to search for */
    @Json(name = "sharedStepsCount")
    val sharedStepsCount: Int64RangeSelectorModel? = null,

    /* Specifies a project range of autotests count to search for */
    @Json(name = "autotestsCount")
    val autotestsCount: Int64RangeSelectorModel? = null,

    /* Specifies a project global IDs to search for */
    @Json(name = "globalIds")
    val globalIds: kotlin.collections.Set<kotlin.Long>? = null,

    /* Specifies a project range of creation date to search for */
    @Json(name = "createdDate")
    val createdDate: DateTimeRangeSelectorModel? = null,

    /* Specifies an autotest creator IDs to search for */
    @Json(name = "createdByIds")
    val createdByIds: kotlin.collections.Set<java.util.UUID>? = null,

    /* Collection of project types to search for */
    @Json(name = "types")
    val types: kotlin.collections.Set<ProjectTypeModel>? = null

) {


}

