/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ru.testit.kotlin.adaptersapi.models

import ru.testit.kotlin.adaptersapi.models.CustomAttributeTypesEnum

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param name Specifies an attribute name to search for
 * @param types Specifies an attribute types to search for
 * @param isRequired Specifies an attribute mandatory status to search for
 * @param isGlobal Specifies an attribute global status to search for
 * @param isEnabled Specifies an attribute enabled status to search for
 */


data class ProjectAttributesFilterModel (

    /* Specifies an attribute name to search for */
    @Json(name = "name")
    val name: kotlin.String,

    /* Specifies an attribute types to search for */
    @Json(name = "types")
    val types: kotlin.collections.Set<CustomAttributeTypesEnum>,

    /* Specifies an attribute mandatory status to search for */
    @Json(name = "isRequired")
    val isRequired: kotlin.Boolean? = null,

    /* Specifies an attribute global status to search for */
    @Json(name = "isGlobal")
    val isGlobal: kotlin.Boolean? = null,

    /* Specifies an attribute enabled status to search for */
    @Json(name = "isEnabled")
    val isEnabled: kotlin.Boolean? = null

) {


}

