/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ru.testit.kotlin.adaptersapi.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id Unique ID of the project
 * @param name Name of the project
 * @param isFavorite Indicates if the project is marked as favorite
 * @param isDeleted Indicates if the project is deleted
 * @param globalId Global ID of the project
 * @param workflowId ID of the workflow used in project
 * @param description Description of the project
 */


data class ProjectApiResult (

    /* Unique ID of the project */
    @Json(name = "id")
    val id: java.util.UUID,

    /* Name of the project */
    @Json(name = "name")
    val name: kotlin.String,

    /* Indicates if the project is marked as favorite */
    @Json(name = "isFavorite")
    val isFavorite: kotlin.Boolean,

    /* Indicates if the project is deleted */
    @Json(name = "isDeleted")
    val isDeleted: kotlin.Boolean,

    /* Global ID of the project */
    @Json(name = "globalId")
    val globalId: kotlin.Long,

    /* ID of the workflow used in project */
    @Json(name = "workflowId")
    val workflowId: java.util.UUID,

    /* Description of the project */
    @Json(name = "description")
    val description: kotlin.String? = null

) {


}

