/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ru.testit.kotlin.adaptersapi.models

import ru.testit.kotlin.adaptersapi.models.AttachmentPutModel
import ru.testit.kotlin.adaptersapi.models.StepPostModel

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param name 
 * @param projectId 
 * @param attachments 
 * @param parentId 
 * @param preconditionSteps 
 * @param postconditionSteps 
 */


data class SectionPostModel (

    @Json(name = "name")
    val name: kotlin.String,

    @Json(name = "projectId")
    val projectId: java.util.UUID,

    @Json(name = "attachments")
    val attachments: kotlin.collections.List<AttachmentPutModel>,

    @Json(name = "parentId")
    val parentId: java.util.UUID? = null,

    @Json(name = "preconditionSteps")
    val preconditionSteps: kotlin.collections.List<StepPostModel>? = null,

    @Json(name = "postconditionSteps")
    val postconditionSteps: kotlin.collections.List<StepPostModel>? = null

) {


}

