/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ru.testit.kotlin.adaptersapi.models

import ru.testit.kotlin.adaptersapi.models.AttachmentModel
import ru.testit.kotlin.adaptersapi.models.StepModel

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param isDeleted 
 * @param id 
 * @param createdDate 
 * @param createdById 
 * @param name 
 * @param attachments 
 * @param preconditionSteps 
 * @param postconditionSteps 
 * @param projectId 
 * @param parentId 
 * @param modifiedDate 
 * @param modifiedById 
 */


data class SectionWithStepsModel (

    @Json(name = "isDeleted")
    val isDeleted: kotlin.Boolean,

    @Json(name = "id")
    val id: java.util.UUID,

    @Json(name = "createdDate")
    val createdDate: java.time.OffsetDateTime,

    @Json(name = "createdById")
    val createdById: java.util.UUID,

    @Json(name = "name")
    val name: kotlin.String,

    @Json(name = "attachments")
    val attachments: kotlin.collections.List<AttachmentModel>? = null,

    @Json(name = "preconditionSteps")
    val preconditionSteps: kotlin.collections.List<StepModel>? = null,

    @Json(name = "postconditionSteps")
    val postconditionSteps: kotlin.collections.List<StepModel>? = null,

    @Json(name = "projectId")
    val projectId: java.util.UUID? = null,

    @Json(name = "parentId")
    val parentId: java.util.UUID? = null,

    @Json(name = "modifiedDate")
    val modifiedDate: java.time.OffsetDateTime? = null,

    @Json(name = "modifiedById")
    val modifiedById: java.util.UUID? = null

) {


}

