/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ru.testit.kotlin.adaptersapi.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param stepId 
 * @param outcome 
 */


data class SharedStepResultApiModel (

    @Json(name = "stepId")
    val stepId: java.util.UUID,

    @Json(name = "outcome")
    val outcome: kotlin.String

) {


}

