/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ru.testit.kotlin.adaptersapi.models

import ru.testit.kotlin.adaptersapi.models.StepModel

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param versionId 
 * @param globalId 
 * @param name 
 * @param steps 
 * @param isDeleted 
 */


data class SharedStepModel (

    @Json(name = "versionId")
    val versionId: java.util.UUID,

    @Json(name = "globalId")
    val globalId: kotlin.Long,

    @Json(name = "name")
    val name: kotlin.String,

    @Json(name = "steps")
    @Deprecated(message = "This property is deprecated.")
    val steps: kotlin.collections.List<StepModel>,

    @Json(name = "isDeleted")
    val isDeleted: kotlin.Boolean

) {


}

