/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ru.testit.kotlin.adaptersapi.models

import ru.testit.kotlin.adaptersapi.models.AttachmentApiResult

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id 
 * @param stepId 
 * @param attachments 
 * @param testResultId 
 * @param createdById 
 * @param createdDate 
 * @param text 
 * @param parentStepId 
 * @param modifiedById 
 * @param modifiedDate 
 */


data class StepCommentApiModel (

    @Json(name = "id")
    val id: java.util.UUID,

    @Json(name = "stepId")
    val stepId: java.util.UUID,

    @Json(name = "attachments")
    val attachments: kotlin.collections.List<AttachmentApiResult>,

    @Json(name = "testResultId")
    val testResultId: java.util.UUID,

    @Json(name = "createdById")
    val createdById: java.util.UUID,

    @Json(name = "createdDate")
    val createdDate: java.time.OffsetDateTime,

    @Json(name = "text")
    val text: kotlin.String? = null,

    @Json(name = "parentStepId")
    val parentStepId: java.util.UUID? = null,

    @Json(name = "modifiedById")
    val modifiedById: java.util.UUID? = null,

    @Json(name = "modifiedDate")
    val modifiedDate: java.time.OffsetDateTime? = null

) {


}

