/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ru.testit.kotlin.adaptersapi.models

import ru.testit.kotlin.adaptersapi.models.AttachmentApiResult
import ru.testit.kotlin.adaptersapi.models.LinkApiResult
import ru.testit.kotlin.adaptersapi.models.TestRunState
import ru.testit.kotlin.adaptersapi.models.TestStatusApiResult

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id Test run unique identifier
 * @param name Test run name
 * @param projectId Project unique identifier              This property is used to link test run with project.
 * @param stateName Test run state
 * @param status Test run status
 * @param attachments Collection of attachments related to the test run
 * @param links Collection of links related to the test run
 * @param tags Collection of tags associated with the test run
 * @param description Test run description
 * @param launchSource Test run launch source              Once launch source is specified it cannot be updated.
 */


data class TestRunApiResult (

    /* Test run unique identifier */
    @Json(name = "id")
    val id: java.util.UUID,

    /* Test run name */
    @Json(name = "name")
    val name: kotlin.String,

    /* Project unique identifier              This property is used to link test run with project. */
    @Json(name = "projectId")
    val projectId: java.util.UUID,

    /* Test run state */
    @Json(name = "stateName")
    @Deprecated(message = "This property is deprecated.")
    val stateName: TestRunState,

    /* Test run status */
    @Json(name = "status")
    val status: TestStatusApiResult,

    /* Collection of attachments related to the test run */
    @Json(name = "attachments")
    val attachments: kotlin.collections.List<AttachmentApiResult>,

    /* Collection of links related to the test run */
    @Json(name = "links")
    val links: kotlin.collections.List<LinkApiResult>,

    /* Collection of tags associated with the test run */
    @Json(name = "tags")
    val tags: kotlin.collections.List<kotlin.String>,

    /* Test run description */
    @Json(name = "description")
    val description: kotlin.String? = null,

    /* Test run launch source              Once launch source is specified it cannot be updated. */
    @Json(name = "launchSource")
    val launchSource: kotlin.String? = null

) {


}

