/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ru.testit.kotlin.adaptersapi.models

import ru.testit.kotlin.adaptersapi.models.AttachmentUpdateRequest

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id Entity unique identifier
 * @param text 
 * @param stepId 
 * @param attachments 
 * @param parentStepId 
 */


data class TestResultStepCommentUpdateRequest (

    /* Entity unique identifier */
    @Json(name = "id")
    val id: java.util.UUID,

    @Json(name = "text")
    val text: kotlin.String,

    @Json(name = "stepId")
    val stepId: java.util.UUID,

    @Json(name = "attachments")
    val attachments: kotlin.collections.List<AttachmentUpdateRequest>,

    @Json(name = "parentStepId")
    val parentStepId: java.util.UUID? = null

) {


}

