/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ru.testit.kotlin.adaptersapi.models

import ru.testit.kotlin.adaptersapi.models.AttachmentApiResult
import ru.testit.kotlin.adaptersapi.models.AutoTest
import ru.testit.kotlin.adaptersapi.models.AutoTestStepResult
import ru.testit.kotlin.adaptersapi.models.LinkApiResult
import ru.testit.kotlin.adaptersapi.models.StepCommentApiModel
import ru.testit.kotlin.adaptersapi.models.StepResultApiModel
import ru.testit.kotlin.adaptersapi.models.TestResultOutcome
import ru.testit.kotlin.adaptersapi.models.TestStatusApiResult

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id 
 * @param failureClassIds 
 * @param configurationId 
 * @param testPointId 
 * @param testRunId 
 * @param stepComments 
 * @param outcome 
 * @param status 
 * @param comment 
 * @param links 
 * @param stepResults 
 * @param attachments 
 * @param autoTestId 
 * @param durationInMs 
 * @param traces 
 * @param failureType 
 * @param message 
 * @param autoTest 
 * @param autoTestStepResults 
 * @param setupResults 
 * @param teardownResults 
 * @param parameters 
 * @param properties 
 */


data class TestResultResponse (

    @Json(name = "id")
    val id: java.util.UUID,

    @Json(name = "failureClassIds")
    val failureClassIds: kotlin.collections.List<java.util.UUID>,

    @Json(name = "configurationId")
    val configurationId: java.util.UUID,

    @Json(name = "testPointId")
    val testPointId: java.util.UUID,

    @Json(name = "testRunId")
    val testRunId: java.util.UUID,

    @Json(name = "stepComments")
    val stepComments: kotlin.collections.List<StepCommentApiModel>? = null,

    @Json(name = "outcome")
    @Deprecated(message = "This property is deprecated.")
    val outcome: TestResultOutcome? = null,

    @Json(name = "status")
    val status: TestStatusApiResult? = null,

    @Json(name = "comment")
    val comment: kotlin.String? = null,

    @Json(name = "links")
    val links: kotlin.collections.List<LinkApiResult>? = null,

    @Json(name = "stepResults")
    val stepResults: kotlin.collections.List<StepResultApiModel>? = null,

    @Json(name = "attachments")
    val attachments: kotlin.collections.List<AttachmentApiResult>? = null,

    @Json(name = "autoTestId")
    val autoTestId: java.util.UUID? = null,

    @Json(name = "durationInMs")
    val durationInMs: kotlin.Long? = null,

    @Json(name = "traces")
    val traces: kotlin.String? = null,

    @Json(name = "failureType")
    val failureType: kotlin.String? = null,

    @Json(name = "message")
    val message: kotlin.String? = null,

    @Json(name = "autoTest")
    val autoTest: AutoTest? = null,

    @Json(name = "autoTestStepResults")
    val autoTestStepResults: kotlin.collections.List<AutoTestStepResult>? = null,

    @Json(name = "setupResults")
    val setupResults: kotlin.collections.List<AutoTestStepResult>? = null,

    @Json(name = "teardownResults")
    val teardownResults: kotlin.collections.List<AutoTestStepResult>? = null,

    @Json(name = "parameters")
    val parameters: kotlin.collections.Map<kotlin.String, kotlin.String>? = null,

    @Json(name = "properties")
    val properties: kotlin.collections.Map<kotlin.String, kotlin.String>? = null

) {


}

