/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ru.testit.kotlin.adaptersapi.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * Values: Failed,InProgress,Incomplete,Succeeded,Pending
 */

@JsonClass(generateAdapter = false)
enum class TestStatusType(val value: kotlin.String) {

    @Json(name = "Failed")
    Failed("Failed"),

    @Json(name = "InProgress")
    InProgress("InProgress"),

    @Json(name = "Incomplete")
    Incomplete("Incomplete"),

    @Json(name = "Succeeded")
    Succeeded("Succeeded"),

    @Json(name = "Pending")
    Pending("Pending");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is TestStatusType) "$data" else null

        /**
         * Returns a valid [TestStatusType] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): TestStatusType? = data?.let {
          val normalizedData = "$it".lowercase()
          values().firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

