/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ru.testit.kotlin.adaptersapi.models

import ru.testit.kotlin.adaptersapi.models.AttachmentUpdateRequest
import ru.testit.kotlin.adaptersapi.models.AutoTestStepResultUpdateRequest
import ru.testit.kotlin.adaptersapi.models.CreateLinkApiModel
import ru.testit.kotlin.adaptersapi.models.StepResultApiModel
import ru.testit.kotlin.adaptersapi.models.TestResultOutcome
import ru.testit.kotlin.adaptersapi.models.TestResultStepCommentUpdateRequest
import ru.testit.kotlin.adaptersapi.models.TestStatusType

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param failureClassIds 
 * @param outcome 
 * @param statusCode 
 * @param statusType 
 * @param comment 
 * @param links 
 * @param stepResults 
 * @param attachments 
 * @param durationInMs 
 * @param duration 
 * @param stepComments 
 * @param setupResults 
 * @param teardownResults 
 * @param message 
 * @param trace 
 */


data class TestResultUpdateRequest (

    @Json(name = "failureClassIds")
    val failureClassIds: kotlin.collections.List<java.util.UUID>? = null,

    @Json(name = "outcome")
    @Deprecated(message = "This property is deprecated.")
    val outcome: TestResultOutcome? = null,

    @Json(name = "statusCode")
    val statusCode: kotlin.String? = null,

    @Json(name = "statusType")
    val statusType: TestStatusType? = null,

    @Json(name = "comment")
    val comment: kotlin.String? = null,

    @Json(name = "links")
    val links: kotlin.collections.List<CreateLinkApiModel>? = null,

    @Json(name = "stepResults")
    val stepResults: kotlin.collections.List<StepResultApiModel>? = null,

    @Json(name = "attachments")
    val attachments: kotlin.collections.List<AttachmentUpdateRequest>? = null,

    @Json(name = "durationInMs")
    @Deprecated(message = "This property is deprecated.")
    val durationInMs: kotlin.Long? = null,

    @Json(name = "duration")
    val duration: kotlin.Long? = null,

    @Json(name = "stepComments")
    val stepComments: kotlin.collections.List<TestResultStepCommentUpdateRequest>? = null,

    @Json(name = "setupResults")
    val setupResults: kotlin.collections.List<AutoTestStepResultUpdateRequest>? = null,

    @Json(name = "teardownResults")
    val teardownResults: kotlin.collections.List<AutoTestStepResultUpdateRequest>? = null,

    @Json(name = "message")
    val message: kotlin.String? = null,

    @Json(name = "trace")
    val trace: kotlin.String? = null

) {


}

