/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ru.testit.kotlin.adaptersapi.models

import ru.testit.kotlin.adaptersapi.models.FailureCategoryModel
import ru.testit.kotlin.adaptersapi.models.Int64RangeSelectorModel
import ru.testit.kotlin.adaptersapi.models.TestResultOutcome
import ru.testit.kotlin.adaptersapi.models.TestStatusApiType

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param configurationIds Specifies a test result configuration IDs to search for
 * @param outcomes Specifies a test result outcomes to search for
 * @param statusCodes Specifies a test result status codes to search for
 * @param statusTypes Specifies a test result status types to search for
 * @param failureCategories Specifies a test result failure categories to search for
 * @param namespace Specifies a test result namespace to search for
 * @param className Specifies a test result class name to search for
 * @param autoTestGlobalIds Specifies an autotest global IDs to search results for
 * @param autoTestTags Specifies autotest tags to include in the search.
 * @param excludeAutoTestTags Specifies autotest tags to exclude from the search.
 * @param name Specifies an autotest name to search results for
 * @param duration Specifies a test result duration range to search for
 * @param testRunIds Specifies a test result test run IDs to search for
 */


data class TestResultsFilterApiModel (

    /* Specifies a test result configuration IDs to search for */
    @Json(name = "configurationIds")
    val configurationIds: kotlin.collections.List<java.util.UUID>? = null,

    /* Specifies a test result outcomes to search for */
    @Json(name = "outcomes")
    @Deprecated(message = "This property is deprecated.")
    val outcomes: kotlin.collections.List<TestResultOutcome>? = null,

    /* Specifies a test result status codes to search for */
    @Json(name = "statusCodes")
    val statusCodes: kotlin.collections.List<kotlin.String>? = null,

    /* Specifies a test result status types to search for */
    @Json(name = "statusTypes")
    val statusTypes: kotlin.collections.List<TestStatusApiType>? = null,

    /* Specifies a test result failure categories to search for */
    @Json(name = "failureCategories")
    val failureCategories: kotlin.collections.List<FailureCategoryModel>? = null,

    /* Specifies a test result namespace to search for */
    @Json(name = "namespace")
    val namespace: kotlin.String? = null,

    /* Specifies a test result class name to search for */
    @Json(name = "className")
    val className: kotlin.String? = null,

    /* Specifies an autotest global IDs to search results for */
    @Json(name = "autoTestGlobalIds")
    val autoTestGlobalIds: kotlin.collections.List<kotlin.Long>? = null,

    /* Specifies autotest tags to include in the search. */
    @Json(name = "autoTestTags")
    val autoTestTags: kotlin.collections.List<kotlin.String>? = null,

    /* Specifies autotest tags to exclude from the search. */
    @Json(name = "excludeAutoTestTags")
    val excludeAutoTestTags: kotlin.collections.List<kotlin.String>? = null,

    /* Specifies an autotest name to search results for */
    @Json(name = "name")
    val name: kotlin.String? = null,

    /* Specifies a test result duration range to search for */
    @Json(name = "duration")
    val duration: Int64RangeSelectorModel? = null,

    /* Specifies a test result test run IDs to search for */
    @Json(name = "testRunIds")
    val testRunIds: kotlin.collections.List<java.util.UUID>? = null

) {


}

