/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ru.testit.kotlin.adaptersapi.models

import ru.testit.kotlin.adaptersapi.models.AssignAttachmentApiModel
import ru.testit.kotlin.adaptersapi.models.UpdateLinkApiModel

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id Test run unique identifier
 * @param name Test run name
 * @param description Test run description
 * @param launchSource Test run launch source              Once launch source is specified it cannot be updated
 * @param attachments Collection of attachments related to the test run
 * @param links Collection of links related to the test run
 * @param tags Collection of tags to assign to the test run
 */


data class UpdateEmptyTestRunApiModel (

    /* Test run unique identifier */
    @Json(name = "id")
    val id: java.util.UUID,

    /* Test run name */
    @Json(name = "name")
    val name: kotlin.String,

    /* Test run description */
    @Json(name = "description")
    val description: kotlin.String? = null,

    /* Test run launch source              Once launch source is specified it cannot be updated */
    @Json(name = "launchSource")
    val launchSource: kotlin.String? = null,

    /* Collection of attachments related to the test run */
    @Json(name = "attachments")
    val attachments: kotlin.collections.List<AssignAttachmentApiModel>? = null,

    /* Collection of links related to the test run */
    @Json(name = "links")
    val links: kotlin.collections.List<UpdateLinkApiModel>? = null,

    /* Collection of tags to assign to the test run */
    @Json(name = "tags")
    val tags: kotlin.collections.List<kotlin.String>? = null

) {


}

