/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ru.testit.kotlin.adaptersapi.models

import ru.testit.kotlin.adaptersapi.models.IterationApiResult
import ru.testit.kotlin.adaptersapi.models.LinkShortApiResult
import ru.testit.kotlin.adaptersapi.models.WorkItemPriorityModel
import ru.testit.kotlin.adaptersapi.models.WorkItemSourceTypeModel
import ru.testit.kotlin.adaptersapi.models.WorkItemStates

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id Work Item internal unique identifier
 * @param name Work Item name
 * @param entityTypeName Work Item type. Possible values: CheckLists, SharedSteps, TestCases
 * @param projectId Project unique identifier
 * @param sectionId Identifier of Section where Work Item is located
 * @param sectionName Section name of Work Item
 * @param isAutomated Boolean flag determining whether Work Item is automated
 * @param globalId Work Item global identifier
 * @param duration Work Item duration
 * @param state The current state of Work Item
 * @param priority Work Item priority level
 * @param sourceType Work Item priority level
 * @param isDeleted Flag determining whether Work Item is deleted
 * @param iterations Set of iterations related to Work Item
 * @param links Set of links related to Work Item
 * @param attributes Work Item attributes
 * @param tagNames Array of tag names of Work Item
 */


data class WorkItemShortApiResult (

    /* Work Item internal unique identifier */
    @Json(name = "id")
    val id: java.util.UUID,

    /* Work Item name */
    @Json(name = "name")
    val name: kotlin.String,

    /* Work Item type. Possible values: CheckLists, SharedSteps, TestCases */
    @Json(name = "entityTypeName")
    val entityTypeName: kotlin.String,

    /* Project unique identifier */
    @Json(name = "projectId")
    val projectId: java.util.UUID,

    /* Identifier of Section where Work Item is located */
    @Json(name = "sectionId")
    val sectionId: java.util.UUID,

    /* Section name of Work Item */
    @Json(name = "sectionName")
    val sectionName: kotlin.String,

    /* Boolean flag determining whether Work Item is automated */
    @Json(name = "isAutomated")
    val isAutomated: kotlin.Boolean,

    /* Work Item global identifier */
    @Json(name = "globalId")
    val globalId: kotlin.Long,

    /* Work Item duration */
    @Json(name = "duration")
    val duration: kotlin.Long,

    /* The current state of Work Item */
    @Json(name = "state")
    val state: WorkItemStates,

    /* Work Item priority level */
    @Json(name = "priority")
    val priority: WorkItemPriorityModel,

    /* Work Item priority level */
    @Json(name = "sourceType")
    val sourceType: WorkItemSourceTypeModel,

    /* Flag determining whether Work Item is deleted */
    @Json(name = "isDeleted")
    val isDeleted: kotlin.Boolean,

    /* Set of iterations related to Work Item */
    @Json(name = "iterations")
    val iterations: kotlin.collections.List<IterationApiResult>,

    /* Set of links related to Work Item */
    @Json(name = "links")
    val links: kotlin.collections.List<LinkShortApiResult>,

    /* Work Item attributes */
    @Json(name = "attributes")
    val attributes: kotlin.collections.Map<kotlin.String, kotlin.Any>? = null,

    /* Array of tag names of Work Item */
    @Json(name = "tagNames")
    val tagNames: kotlin.collections.List<kotlin.String>? = null

) {


}

