/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ru.testit.kotlin.adaptersapi.models

import ru.testit.kotlin.adaptersapi.models.TestStatusApiType

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id 
 * @param code 
 * @param type Collection of possible status types
 */


data class WorkflowStatusApiResult (

    @Json(name = "id")
    val id: java.util.UUID,

    @Json(name = "code")
    val code: kotlin.String,

    /* Collection of possible status types */
    @Json(name = "type")
    val type: TestStatusApiType

) {


}

