/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ru.testit.kotlin.adaptersapi.models

import ru.testit.kotlin.adaptersapi.models.AttachmentModel
import ru.testit.kotlin.adaptersapi.models.AutoTestModel
import ru.testit.kotlin.adaptersapi.models.IterationModel
import ru.testit.kotlin.adaptersapi.models.LinkModel
import ru.testit.kotlin.adaptersapi.models.StepModel
import ru.testit.kotlin.adaptersapi.models.TagModel
import ru.testit.kotlin.adaptersapi.models.WorkItemEntityTypeApiModel
import ru.testit.kotlin.adaptersapi.models.WorkItemParameterKeyApiResult
import ru.testit.kotlin.adaptersapi.models.WorkItemPriorityApiModel
import ru.testit.kotlin.adaptersapi.models.WorkItemStateApiModel

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id Unique identifier of the work item
 * @param globalId Global identifier of the work item
 * @param projectId Unique identifier of the project
 * @param sectionId Unique identifier of the section within a project
 * @param name Name of the work item
 * @param entityTypeName Type of entity associated with this work item
 * @param duration Duration of the work item in milliseconds
 * @param state State of the work item
 * @param priority Priority level of the work item
 * @param isAutomated 
 * @param attributes Set of custom attributes associated with the work item
 * @param tags Set of tags applied to the work item
 * @param sectionPreconditionSteps Set of section precondition steps that need to be executed before starting the work item steps
 * @param sectionPostconditionSteps Set of section postcondition steps that need to be executed after completing the work item steps
 * @param preconditionSteps Set of precondition steps that need to be executed before starting the main steps
 * @param steps Main steps or actions defined for the work item
 * @param postconditionSteps Set of postcondition steps that are executed after completing the main steps
 * @param iterations Associated iterations linked to the work item
 * @param autoTests Automated tests associated with the work item
 * @param attachments Files attached to the work item
 * @param links Set of links related to the work item
 * @param parameters Set of parameters related to the work item
 * @param isDeleted Indicates whether the work item is marked as deleted
 * @param description Description of the work item
 */


data class WorkItemApiResult (

    /* Unique identifier of the work item */
    @Json(name = "id")
    val id: java.util.UUID,

    /* Global identifier of the work item */
    @Json(name = "globalId")
    val globalId: kotlin.Long,

    /* Unique identifier of the project */
    @Json(name = "projectId")
    val projectId: java.util.UUID,

    /* Unique identifier of the section within a project */
    @Json(name = "sectionId")
    val sectionId: java.util.UUID,

    /* Name of the work item */
    @Json(name = "name")
    val name: kotlin.String,

    /* Type of entity associated with this work item */
    @Json(name = "entityTypeName")
    val entityTypeName: WorkItemEntityTypeApiModel,

    /* Duration of the work item in milliseconds */
    @Json(name = "duration")
    val duration: kotlin.Int,

    /* State of the work item */
    @Json(name = "state")
    val state: WorkItemStateApiModel,

    /* Priority level of the work item */
    @Json(name = "priority")
    val priority: WorkItemPriorityApiModel,

    @Json(name = "isAutomated")
    val isAutomated: kotlin.Boolean,

    /* Set of custom attributes associated with the work item */
    @Json(name = "attributes")
    val attributes: kotlin.collections.Map<kotlin.String, kotlin.Any>,

    /* Set of tags applied to the work item */
    @Json(name = "tags")
    val tags: kotlin.collections.List<TagModel>,

    /* Set of section precondition steps that need to be executed before starting the work item steps */
    @Json(name = "sectionPreconditionSteps")
    val sectionPreconditionSteps: kotlin.collections.List<StepModel>,

    /* Set of section postcondition steps that need to be executed after completing the work item steps */
    @Json(name = "sectionPostconditionSteps")
    val sectionPostconditionSteps: kotlin.collections.List<StepModel>,

    /* Set of precondition steps that need to be executed before starting the main steps */
    @Json(name = "preconditionSteps")
    val preconditionSteps: kotlin.collections.List<StepModel>,

    /* Main steps or actions defined for the work item */
    @Json(name = "steps")
    val steps: kotlin.collections.List<StepModel>,

    /* Set of postcondition steps that are executed after completing the main steps */
    @Json(name = "postconditionSteps")
    val postconditionSteps: kotlin.collections.List<StepModel>,

    /* Associated iterations linked to the work item */
    @Json(name = "iterations")
    val iterations: kotlin.collections.List<IterationModel>,

    /* Automated tests associated with the work item */
    @Json(name = "autoTests")
    val autoTests: kotlin.collections.List<AutoTestModel>,

    /* Files attached to the work item */
    @Json(name = "attachments")
    val attachments: kotlin.collections.List<AttachmentModel>,

    /* Set of links related to the work item */
    @Json(name = "links")
    val links: kotlin.collections.List<LinkModel>,

    /* Set of parameters related to the work item */
    @Json(name = "parameters")
    val parameters: kotlin.collections.List<WorkItemParameterKeyApiResult>,

    /* Indicates whether the work item is marked as deleted */
    @Json(name = "isDeleted")
    val isDeleted: kotlin.Boolean,

    /* Description of the work item */
    @Json(name = "description")
    val description: kotlin.String? = null

) {


}

