name: Publish
on:
  release:
    types:
      - released

jobs:

  # Prepare and publish the plugin
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:

      # Check out current repository
      - name: Fetch Sources
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.release.tag_name }}

      # Set up Java environment for the next steps
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 17

      # Setup Gradle
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      # Build plugin for PyCharm
      - name: Build Plugin for PyCharm
        run: |
          ./gradlew buildPlugin -PisPyCharm=true --no-build-cache --no-configuration-cache
          for f in testit_management-*.zip; do mv "$f" "${f/testit_management-/testit_management_PyCharm-}"; done

      # Build plugin for IDEA
      - name: Build Plugin for IDEA
        run: | 
          ./gradlew buildPlugin -PisIDEA=true --no-build-cache --no-configuration-cache
          for f in testit_management-*.zip; do mv "$f" "${f/testit_management-/testit_management_IDEA-}"; done

      - name: Upload Release Asset
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release upload ${{ github.event.release.tag_name }} ./build/distributions/*
