name: Publish
on:
  release:
    types:
      - released

jobs:

  # Prepare and publish the plugin
  release:
    name: Publish Plugin
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:

      # Check out current repository
      - name: Fetch Sources
        uses: actions/checkout@v4

      # Set up Java environment for the next steps
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 17

      # Setup Gradle
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-home-cache-cleanup: true

      # Build plugin
      - name: Build plugin
        run: |
          ./gradlew buildPlugin
          cd ${{ github.workspace }}/build/distributions
          FILENAME=`ls *.zip`
          echo "filename=${FILENAME:0:-4}" >> $GITHUB_OUTPUT

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ github.workspace }}/build/distributions/${{ steps.artifact.outputs.filename }}.zip
          asset_name: ${{ steps.artifact.outputs.filename }}.zip
          tag: ${{ github.ref }}
          overwrite: true
