name: Draft

on:
  push:
    branches: [ "main" ]

jobs:

  update:
    name: Update
    runs-on: ubuntu-latest
    steps:

      - name: Update Draft Release
        uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}